### DISCUSSION TITLE
Kubectl, but mostly .Env

### DISCUSSION THREAD

**Discussion by akelge** [JanDeDobbeleer/oh-my-posh#1507] [Troubleshoot]
I have this segment in my theme:
```
  - type: kubectl
    style: plain
    foreground: lightBlue
    properties:
      display_error: true
      parse_kubeconfig: true
      postfix: ""
      prefix: ""
      # template: '{{if eq "on" .Env.KUBE_PS1_ENABLED}} {{.Context}}{{if .Namespace}}/{{.Namespace}}{{end}}{{end}}'
      template: '{{if eq "on" .Env.KUBE_PS1_ENABLED}} {{.Context}}/{{.Namespace}}{{end}}'
      # template: '{{ .Context }}/{{ .Namespace }}'
```
I don't want/need to show always the Kubectl related parts, I have an alias `kubeon` that sets the var to on and a `kubeoff` that sets the var to `off`.
The third template works fine (but is not what I want), the first shows always Namespace as default, the third one shows empty Namespace (this is coherent indeed).
I am quite sure it was working till a couple of versions ago, now it stopped working.
Anyone has any hint?
