### DISCUSSION TITLE
Segments randomly missing from the cache

### DISCUSSION THREAD

**Discussion by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2885] [General]
For cross-segment template references, OMP caches segment data via `(*environment.TemplateCache).AddSegmentData`. However, this does not seem to work well. I tested it (e.g., `{{.Segments.Exit.Meaning}}`) on Windows/Linux and I found that every time OMP updates the cache file, some segments are randomly missing from the cached `Segments` map, which makes a cross-segment template not always available.

**Comment by lewis-yeung** [comment]
I've looked through the code but couldn't find the source of the problem.

**Reply by JanDeDobbeleer** [reply]
I honestly never noticed that, have multiple segments with this functionality. What could happen is that when using multiple sessions (tabs, etc), it overwrites the cache and it doesn't really work for transient or another. Other than that, I don't see an immediate reason why this would occur.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I tested it in PowerShell by continuously pressing <kbd>Ctrl</kbd> + <kbd>L</kbd> to redraw the prompt, and I noticed that an expected `0` didn't always show up in the `time` segment where I utilized `{{.Segments.Exit.Meaning}}`.

<details><summary>The custom theme I use for tests:</summary>

```yaml
palette:
  darkOliveGreen: "#556b2f"
  chocolate: "#d2691e"
  teal: "#008080"
  dodgerBlue: "#1e90ff"
blocks:
  - alignment: left
    segments:
      - foreground: white
        style: plain
        template: ╭─
        type: text
      - background: blue
        foreground: white
        leading_diamond: 
        style: diamond
        template: " {{if .WSL}}[<lightGreen>WSL</>]{{end}}{{.Icon}}  <lightYellow>{{.Shell}}</> "
        type: os
      - background: white
        foreground: black
        powerline_symbol: 
        style: powerline
        template: " {{if .SSHSession}} {{end}}{{if .Root}} {{else}} {{end}}<p:dodgerBlue><b>{{.UserName}}</b></><green>@</> <p:chocolate><b>{{.HostName}}</b></> "
        type: session
      - background: p:teal
        foreground: white
        style: powerline
        powerline_symbol: 
        template: "{{.Segments.Exit.Meaning}}  {{.CurrentDate | date .Format}} "
        type: time
      - background_templates:
          - "{{if ne .Code 0}}red{{else}}green{{end}}"
        foreground: white
        properties:
          always_enabled: true
        powerline_symbol: 
        style: powerline
        template: " {{if ne .Code 0}} {{.Code}}{{else}} ✔{{end}} "
        type: exit
      - background: p:darkOliveGreen
        foreground: white
        properties:
          always_enabled: true
        powerline_symbol: 
        style: powerline
        template: "{{if ne .Ms 0}}  {{.FormattedMs}} {{end}}"
        type: executiontime
      - background: magenta
        foreground: white
        properties:
          style: folder
          mapped_locations_enabled: false
          mapped_locations:
            "~": "~"
        style: diamond
        template: " {{if gt .StackCount 0}}[<lightGreen><b>{{.StackCount}}</b></>] {{end}} {{.Parent}}<lightGreen>{{.Path}}</> "
        trailing_diamond: 
        type: path
    type: prompt
  - alignment: left
    newline: true
    segments:
      - style: plain
        template: "╰─<lightGreen></> "
        type: text
    type: prompt
console_title_template: "{{if .Root}}*{{end}}{{.Shell}} | {{.UserName}}@{{.HostName}} | {{.PWD}}"
secondary_prompt:
  foreground: darkGray
  template: "»»» "
valid_line:
  foreground: lightGreen
  template: " "
error_line:
  foreground: lightRed
  template: " "
transient_prompt:
  template: "<lightGreen> </> "
version: 2
```

</details>

**Reply by lewis-yeung** [reply]
@JanDeDobbeleer Have you tested this case? I just kept pressing <kbd>Ctrl</kbd> + <kbd>L</kbd> in PowerShell to spawn new prompts and it was still broken with the latest version on my end.

**Reply by lewis-yeung** [reply]
Besides, I found the bug occurs more often on Windows (broken cases > normal cases) than on Linux (broken cases < normal cases), and I'm sure it's not shell-specific.

**Reply by JanDeDobbeleer** [reply]
@lewis-yeung I didn't validate this yet, no. Could be that concurrent writes to the cache cause this.

**Comment by lewis-yeung** [comment]
> Could be that concurrent writes to the cache cause this.

After some debugging and tests, I finally found the culprit for this. 👻 It's not exactly a concurrent cache-writing issue, but associated with concurrency (Goroutines) indeed. Let's consider this call hierarchy:

`(*engine.Block).setEnabledSegments` -[(1)][call-1]-> `(*engine.Segment).SetEnabled` -[(2)][call-2]-> `(*platform.Shell).TemplateCache`

The keypoint is that `env.TemplateCache()` (actually, `Shell.tmplCache`) in [(2)][call-2] does not always point to the same instance of `TemplateCache`.

In [(1)][call-1], one Goroutine is created for each segment's `SetEnabled` logic. Of course, [this check](https://github.com/JanDeDobbeleer/oh-my-posh/blob/9dd462c0d0c3eb45fcc640bac683ecdc33d4d4d8/src/platform/shell.go#L712) will fail for the first call. After a new instance of `TemplateCache` is created in a Goroutine but before [`env.tmplCache = tmplCache`](https://github.com/JanDeDobbeleer/oh-my-posh/blob/9dd462c0d0c3eb45fcc640bac683ecdc33d4d4d8/src/platform/shell.go#L749) is executed, another Goroutine does not know its existence, so the above check may still fail and the early return will not be executed. That way different Goroutines may create more than one instance of `TemplateCache` in total, but only one will be finally preserved and be written to the cache file (omp.cache), and not all segments are added into this instance of `TemplateCache`. Thus once a new prompt is generated, there can be some segments randomly missing from the cached `Segments` map.

Make a change in block.go like the following (i.e., to remove the concurrency) is a feasible solution: (validated)

```diff
--- a/src/engine/block.go
+++ b/src/engine/block.go
@@ -109,10 +109,8 @@ func (b *Block) setEnabledSegments() {
        wg.Add(len(b.Segments))
        defer wg.Wait()
        for _, segment := range b.Segments {
-               go func(s *Segment) {
-                       defer wg.Done()
-                       s.SetEnabled(b.env)
-               }(segment)
+               segment.SetEnabled(b.env)
+               wg.Done()
        }
 }
```

Perhaps there is a better option. @JanDeDobbeleer Any ideas?

[call-1]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/9dd462c0d0c3eb45fcc640bac683ecdc33d4d4d8/src/engine/block.go#L114
[call-2]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/9dd462c0d0c3eb45fcc640bac683ecdc33d4d4d8/src/engine/segment.go#L413

**Reply by JanDeDobbeleer** [reply]
@lewis-yeung we just need to sync the creation and assignment of the templatecache in this case.

**Reply by lewis-yeung** [reply]
@JanDeDobbeleer Will you fix it?

**Reply by lewis-yeung** [reply]
@JanDeDobbeleer I noticed that you had tried to [fix](https://github.com/JanDeDobbeleer/oh-my-posh/commit/73e91eab5ba0aa659f568df1f63ab3c6ebb15c56) this using R/W lock inside `(*platform.Shell).TemplateCache`. Actually, I had already tested this way and knew it could introduce a deadlock before I posted the long comment above. Sorry that I didn't mention this earlier. So as an alternative, should we just remove the concurrency in `(*engine.Block).setEnabledSegments`? Or should we add a specific R/W lock in the type definition of `TemplateCache` instead of just using a [global](https://github.com/JanDeDobbeleer/oh-my-posh/blob/3cdb3bfc1dc8b748b8911bcf80bce2878a921ad9/src/platform/shell.go#L45) one? IMO, it's not a good idea to share a global lock between methods of different data types (`Shell`, `TemplateCache` and `concurrentMap`), though in a way it can be by design.

**Reply by JanDeDobbeleer** [reply]
@lewis-yeung we can indeed try a local one. I'm not sure why I designed it this way, can be the wrong solution. I want to keep the parallelism as it's s bit faster.

**Reply by JanDeDobbeleer** [reply]
@lewis-yeung I refactored that and fixed it. It was because `PWD()` also locks and that one's called from `TemplateCache()` so that lock could be removed as we call `TemplateCache()` before `PWD()`

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I noticed that this bug has reappeared since the commit 4e19379e196944e000b6538e44ad941ab6b1ab41 in which you tried to fix another [bug](https://github.com/JanDeDobbeleer/oh-my-posh/issues/3646).

**Reply by JanDeDobbeleer** [reply]
Maybe we should then not execute in parallel. Not sure if there's a lot of benefit anymore nowadays.

**Reply by lewis-yeung** [reply]
I have got a fix that also preserves concurrency, will put it up later. :)

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer The problem reappears in v24. Still broken in v24.0.11. :(

**Reply by JanDeDobbeleer** [reply]
Segments is a `sync.Map` so it shouldn't happen really. It's always added when enabled, the logic is rather straightforward.

**Reply by JanDeDobbeleer** [reply]
By which I'm not saying it can't, but it definitely shouldn't. It's built for concurrency...

**Reply by lewis-yeung** [reply]
Something must be off there, while I don't have a moment to debug deeper and fix it now.

**Reply by JanDeDobbeleer** [reply]
@lewis-yeung I tried to reproduce this last time and couldn't, theoretically, when the segment is enabled, it will also be added to the template cache.

**Reply by lewis-yeung** [reply]
Using a minimal example config as below:

```yaml
version: 3
patch_pwsh_bleed: true
final_space: true
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: text
        alias: foo
        style: plain
        template: '***'
      - type: text
        style: plain
        template: ->{{.Segments.foo.Text}}<-
      - type: text
        style: plain
        template: bar|
      - type: text
        style: plain
        template: baz|
```

I tested **on Windows** with just holding <kbd>Enter</kbd> to emit new prompts, and got some prompts with `***` missing between `->` and `<-`:

![screenshot](https://github.com/user-attachments/assets/025418ae-c6cf-46f7-86f6-6089fd7f46d0)

@JanDeDobbeleer As my [previous comment][comment] said, it can be at least easily reproduced **on Windows**, but hardly on Linux without adding more segments.

I guess there may be a similar root cause.

[comment]: https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2885#discussioncomment-4005655
