### DISCUSSION TITLE
How to remove leading and trailing spaces from plain block

### DISCUSSION THREAD

**Discussion by JustinGrote** [JanDeDobbeleer/oh-my-posh#3089] [Troubleshoot] [answered]
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space: true
version: 2

blocks:
  - type: prompt
    alignment: left

    segments:
      - type: path
        style: plain
        background: "#333333"
        properties:
          home_icon: 🏠
          mapped_locations_enabled: true
          mapped_locations:
            "~/Projects": "🚧"
            "~/Documents": "📄"
            "~": "🏠"
          mixed_threshold: 4
          hide_root_location: false
          prefix: 'aaa'
          postfix: 'aaa'
      - type: text
        style: plain
        prefix: 'a'
        postfix: 'a'
        background: "transparent"
        foreground: "#333333"
        template: ""

  - type: prompt
    alignment: left
    newline: true
    segments:
      # - type: exit
      #   style: diamond
      #   foreground: "#ffffff"
      #   background: "#ff0000"
      #   properties:
      #     always_enabled: true
      #     error_symbol: "✖"
      #     success_symbol: ""
      #     show_exit_code: false
      #     show_symbol: true
      - type: text
        style: plain
        foreground: "green"
        template: "❯"

valid_line:
  background: "transparent"
  foreground: "#ffffff"
  template: "<green>❯ </>"

error_line:
  background: "transparent"
  foreground: "#ffffff"
  template: "<red>❯ </>"
```
![image](https://user-images.githubusercontent.com/15258962/202319119-d6409b91-0c34-47c1-8573-135559c65a21.png)

The docs: https://ohmyposh.dev/docs/configuration/segment#plain say to use `prefix` and `postfix` but they dont seem to work nor are they in the json schema. I can't get this to work with powerline either. Any thoughts?
