### DISCUSSION TITLE
parentForeground does not work for me

### DISCUSSION THREAD

**Discussion by kekscode** [JanDeDobbeleer/oh-my-posh#3227] [Troubleshoot] [answered]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I read the docs at https://ohmyposh.dev/docs/configuration/colors#standard-colors and as far as i understand the `text` segment in the `rprompt` should be able to inherit the color from the element next to it by using `parentForeground` (see the `FIXME` comment in my config).

The idea is: This way, the color of the `\ue0c2` char should always have the correct color. In my case, it is not displayed at all. The `oh-my-posh debug` does show the symbol though which confuses me further. Maybe i am just completely misinterpreting what `[...] can be used to inherit the previous active segment's foreground color.` from the docs actually mean. Any suggestions?

Debug shows the missing symbol:

![image](https://user-images.githubusercontent.com/803252/208685639-03c7cf1b-afce-4eb4-9821-a6af9942df06.png)

But it is missing in the actual prompt at the very left of the right-aligned prompt:

![image](https://user-images.githubusercontent.com/803252/208685788-e91b0b21-9230-4212-ab53-131039361b91.png)

My details:

- oh-my-posh version `12.28.0` from homebrew on MacOS 13.1
- shell is zsh 5.9
- font is hack nerd font

### Theme

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
# A oh-my-posh terminal prompt theme with nord colors
version: 2
palette:
  # https://www.nordtheme.com/docs/colors-and-palettes
  default: "#ECEFF4"
  black: "#2E3440"
  blue: "#5E81AC"
  cyan: "#8FBCBB"
  darkGray: "#4C566A"
  green: "#A3BE8C"
  magenta: "#B48EAD"
  orange: "#D08770"
  purple: "#B48EAD"
  red: "#BF616A"
  white: "#D8DEE9"
  yellow: "#EBCB8B"
  lightBlue: "#81A1C1"
  lightWhite: "#ECEFF4"
transient_prompt:
  background: transparent
  foreground: p:blue
  template: "\ue0c0 "
blocks:
  - alignment: left
    type: prompt
    newline: false
    segments:
      - type: path
        style: powerline
        background: "p:blue"
        foreground: "p:white"
        properties:
          style: agnoster_full
      - type: text
        style: powerline
        background: transparent
        foreground: p:blue
        template: "\ue0c0 "
  - alignment: right
    type: rprompt
    segments:
      - type: text
        style: powerline
        background: transparent
        foreground: parentForeground
        # FIXME: This does not work (character is not shown):
        template: "\ue0c2"
      - type: kubectl
        style: powerline
        background: "p:blue"
        foreground: "p:white"
        template: " ﴱ {{.Context}} ({{if .Namespace}}{{.Namespace}}{{else}}default{{end}}) "
      - type: git
        style: powerline
        background: "p:yellow"
        foreground: "p:black"
        properties:
          fetch_status: true
          fetch_stash_count: true
          fetch_upstream_icon: false
        template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }}{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}} \uF692 {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}} \uf1bb {{ .WorktreeCount }}{{ end }} "
        background_templates:
          - "{{ if or (.Staging.Changed) (.Working.Changed) }}p:yellow{{ end }}"
          - "{{ if or (not .Staging.Changed) (not .Working.Changed) }}p:green{{ end }}"
      - type: executiontime
        style: powerline
        background: "p:orange"
        foreground: "p:black"
        format: austin
      - type: exit
        style: powerline
        background: "p:red"
        foreground: "p:black"
        template: " {{ if gt .Code 0 }} {{ .Meaning }}{{ else }}{{ end }} "

```

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
I would have to curate the log output a lot right now. If the issue is not clear and the full output is actually needed, i'd be happy to provide it later on.
```
