### DISCUSSION TITLE
Full window-width bar in transient prompt

### DISCUSSION THREAD

**Discussion by forrestfwilliams** [JanDeDobbeleer/oh-my-posh#3708] [Troubleshoot]
In my `zsh` prompt, I would like to make a transient prompt that is a bar which spans the full width of my command prompt window, regardless of window size. Ideally it would look something like this:

<img width="928" alt="Screen Shot 2023-04-12 at 7 11 59 AM" src="https://user-images.githubusercontent.com/31411324/231453196-55c8f870-9274-440f-942d-873a87304354.png">

I can create this transient prompt using a pre-defined width:
```yaml
transient_prompt:
  foreground: "#9ece6a"
  template: "{{ repeat 105 \"—\" }}\n"
```
But I can't figure out how to make the bar length dynamic so that it always fits my window size. Does anyone have suggestions on how I could accomplish this? Thanks!

**Comment by JanDeDobbeleer** [comment]
@forrestfwilliams transient prompt doesn't know about this length. But we do have a feature in a regular prompt called [filler](https://ohmyposh.dev/docs/configuration/block#filler) that does this for right aligned blocks. I could expose this for transient as well so that it fills the entire line with a set of config defined characters. I can have a look once I'm back from my holidays.

**Reply by forrestfwilliams** [reply]
That sounds like a great solution! Yes it would be great to have that option exposed in transient prompts.

**Reply by JanDeDobbeleer** [reply]
@forrestfwilliams https://github.com/JanDeDobbeleer/oh-my-posh/pull/3721

**Comment by forrestfwilliams** [comment]
@JanDeDobbeleer thanks for the update! I've upgraded to version `14.30.0`. Could you confirm that the configuration below should produce a solid line transient prompt? Currently, this configuration only produces a single dash for me.

```yaml
transient_prompt:
  foreground: "#a9b1d6"
  template: "—\n"
  filler: "—"
```

I also tried it as:

```yaml
transient_prompt:
  foreground: "#a9b1d6"
  alignment: right
  template: "—\n"
  filler: "—"
```

But got the same result.
