### DISCUSSION TITLE
Missing leading "/" in {{ .Path }} when style is not full

### DISCUSSION THREAD

**Discussion by clyra** [JanDeDobbeleer/oh-my-posh#3946] [Troubleshoot] [answered]
Hi all,

I'm trying to figure out why the path segment is hiding the leading "/" when the property style is not "full". So,  "/usr/local" shows as "usr/local". For example:

```
- type: path
  background: "p:bg"
  foreground: "p:fg"
  properties:
  folder_icon: "\uf115"
  max_width: 40
  style: full
  style: plain
  template: " {{ .Path }} "
```

works a expected:
![Captura de Tela 2023-06-10 às 10 23 51](https://github.com/JanDeDobbeleer/oh-my-posh/assets/4778266/57d4315f-3f81-46f4-a0f6-dadd742b45c0)

But changing "style: full" to "style: powerlevel" show as:

![Captura de Tela 2023-06-10 às 10 24 46](https://github.com/JanDeDobbeleer/oh-my-posh/assets/4778266/e3a19f8d-83ed-4833-b5d1-9b5f3026e5f7)

Other styles as agnoster_*, and unique results in the same missing leading "/". What I'm doing wrong? Btw, I'm using oh-my-posh version 16.10.0 on Monterey and this happens both with fish and nushell.

thx

**Comment by JanDeDobbeleer** [comment]
@clyra nothing, this is by design. powerlevel expects a custom path separator which defaults to `/`, but that's not really the intent.

**Reply by clyra** [reply]
oh.. ok. I can get around this using a template like: 

```
template: "{{ if matchP \"~\" .Path }}{{.Path}}{{else}}/{{ .Path }}{{end}} "
```

But my ultimate goal is to mimic what I have with oh-my-zsh + powerlevel10k like the image below:
![Captura de Tela 2023-06-10 às 18 30 08](https://github.com/JanDeDobbeleer/oh-my-posh/assets/4778266/30569a79-2395-4216-b12d-028e721cea3a)

Upper terminal is powerlevel10k, lower terminal is omp. The first and last part of the path is in bold style. Any tips?

**Reply by JanDeDobbeleer** [reply]
@clyra the colors can be done by leveraging the `cycle` property on the `path` segment . There's no support for text decorations there yet though.

**Reply by clyra** [reply]
thanks, i will look into the cycle property. Meanwhile I had limited success with:

```
template: "{{ if not .Parent }} ~ {{ else }} {{ .Parent }}<b><p:diranchorfg>{{ .Folder }}</></b> {{end}}"
```

But with this template I loose the path shortening features:

![Captura de Tela 2023-06-11 às 15 25 36](https://github.com/JanDeDobbeleer/oh-my-posh/assets/4778266/d419c9d8-c7e1-439c-8f44-44516415c628)

The "not yet" part sounds promising too :-). Thanks again.

**Reply by JanDeDobbeleer** [reply]
@clyra https://github.com/JanDeDobbeleer/oh-my-posh/pull/3962

**Reply by clyra** [reply, marked as answer]
omp! so cool :-). thanks!

**Reply by clyra** [reply]
Hi, 

First, let me thank you again for this feature, but I just found a minor issue that you may want to look into. When the path is short enough, everything works as expected, but on longer paths, the part that was shortened uses a different style. I'm using the following configuration:

```
- type: path
   background: "p:bg"
   foreground: "p:fg"
   properties:
       folder_icon: "\uf115"
       max_width: 40
       style: powerlevel
       edge_format: "p:diranchorfg"
   style: plain
   template: "{{ .Path }}"
```

And seeing this:

![Captura de Tela 2023-06-15 às 19 10 34](https://github.com/JanDeDobbeleer/oh-my-posh/assets/4778266/9ad72ce6-afdc-4343-99dd-8c192ab8588a)

So, "/.config/" has the p:fg style, but the shortned. "/v/" uses something else...
