### DISCUSSION TITLE
Is there any way to nest <p:color> tags?

### DISCUSSION THREAD

**Discussion by Destroy666x** [JanDeDobbeleer/oh-my-posh#4228] [Troubleshoot] [answered]
Nesting doesn't seem to work for me, as in the nested `<p:color>` also stops coloring the parent one. Is that intended?

Example:
```
"<p:{{ if .Working.Changed }}git_unstaged{{ else if .Staging.Changed }}git_staged{{ else }}default{{ end }}>test {{ .HEAD }}</>"
```
+
```
branch_icon: "<p:icon>\uE725</> "
```

Results only in `test` colored:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/3606072/c8d35a3f-82b9-469c-8442-f34b13aea7ff)

**Comment by JanDeDobbeleer** [comment]
@Destroy666x correct, we do not keep track of which colors have been added so this will always reset to the Segment color(s) in this use-case. This is easier to achieve using `foreground_templates` if that's the entire `template`:

```json
{
    "foreground_templates": [
         "{{ if .Working.Changed }}p:git_unstaged{{ else if .Staging.Changed }}p:git_staged{{ else }}p:default{{ end }}"
    ],
    "properties": {
         "branch_icon": "<p:icon>\uE725</> "
    },
    "template": "test {{ .HEAD }}"

**Reply by Destroy666x** [reply]
It's not a whole single template unfortunately, just one of few templates in `templates` array

**Reply by JanDeDobbeleer** [reply]
@Destroy666x I have this implemented. Took me 3 tries to finally see the light.

**Reply by Destroy666x** [reply]
Awesome, thanks!

**Reply by Destroy666x** [reply]
@JanDeDobbeleer thanks, but unfortunately, I tested latest version now and it resulted in:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/3606072/5ccfd2de-2278-4862-bf49-05cbbd016ffc)
again. What would be a working example?

**Reply by JanDeDobbeleer** [reply]
@Destroy666x can you give me the entire segment for reference?

**Reply by Destroy666x** [reply]
Sure:
```
      - type: git
        style: plain
        templates:
          - "<p:url><b>{{ url .UpstreamIcon .UpstreamURL }}</b></><p:icon>{{ if .IsBare }}\U000F0F52 {{ end }}{{ if .IsWorkTree }}\U000F0645{{ .WorktreeCount }} {{ end }}</>"
          - "<p:{{ if .Working.Changed }}git_unstaged{{ else if .Staging.Changed }}git_staged{{ else }}default{{ end }}>test {{ .HEAD }}</> "
          - "<b>{{if .BranchStatus }}{{ .BranchStatus }} {{ end }}{{ if .Working.Changed }}<p:icon>\U000F1323</> {{ .Working.String }} {{ end }}"
          - "{{ if .Staging.Changed }}<p:icon>\U000F042F</> {{ .Staging.String }} {{ end }}{{ if .StashCount }}<p:icon>\U000F0194</>{{ .StashCount }} {{ end }}</b>"
          - "<p:icon>\U000F1173</> {{ trim (trunc .Var.GitCommitMaxLength .Commit.Subject) }}{{ if gt (len .Commit.Subject) .Var.GitCommitMaxLength }}...{{ end }} "
          - "<p:datetime>{{ date .Var.GitCommitDateFormat .Commit.Timestamp }}</>"
        properties:
          branch_max_length: 30
          fetch_bare_info: true
          fetch_status: true
          fetch_upstream_icon: true
          truncate_symbol: ...
          status_formats:
            Added: "<p:icon>\U000F0415</>%d"
            Deleted: "<p:icon>\U000F0415</>%d"
            Modified: "<p:icon>\U000F0992</>%d"
            Unmerged: "<p:icon>\U000F00F8</>%d"
            Untracked: "<p:icon>\U000F0209</>%d"
          branch_ahead_icon: "<p:icon>\u21B1</>"
          branch_behind_icon: "<p:icon>\u21B2</>"
          branch_gone_icon: "<p:icon>\uEABD</>"
          branch_icon: "<p:icon>\uE725</> "
          branch_identical_icon: "<p:icon>\uF44E</>"
          cherry_pick_icon: "<p:icon>\U000F1042</>"
          commit_icon: "<p:icon>\uF417</>"
          git_icon: "\uE702"
          merge_icon: "<p:icon>\uE727</> "
          no_commits_icon: "<p:icon>\U000F0394</>"
          rebase_icon: "<p:icon>\uEBAB</> "
          revert_icon: "<p:icon>\uF0E2</>"
          tag_icon: "<p:icon>\uF02B</> "
```

```
palettes:
  template: '{{ if eq .Env.OMP_THEME "simple_dark" }}simple_dark{{ else }}accent_dark{{ end }}'
  list:
    accent_dark:
      default: default
      error: red
      info: cyan
      success: green
      warning: yellow
      datetime: blue
      git_staged: green
      git_unstaged: yellow
      icon: accent
      url: magenta
    simple_dark:
      default: default
      error: red
      info: white
      success: green
      warning: yellow
      datetime: white
      git_staged: green
      git_unstaged: yellow
      icon: white
      url: magenta

var:
  GitCommitMaxLength: 40
  GitCommitDateFormat: "2 Jan, 15:04"
```
