### DISCUSSION TITLE
A way to truncate the current folder name if too long?

### DISCUSSION THREAD

**Discussion by Artemis-Hound** [JanDeDobbeleer/oh-my-posh#4533] [Troubleshoot] [answered]
Hi, I'm looking for a way to modify the configuration for the Path segment so that if the folder name is over a certain length it truncates it, preferably with a "...", as some folder names end up taking up too much real estate:

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/10010491/1d821747-75e4-427d-9961-20e50b94bb37)

My current configuration is using `"style": "folder"`, but I could not find any properties I could configure for this, besides maybe `max_width`, but that only seems to work for Powerlevel style.

<details>
  <summary>My current Path segment configuration:</summary>

  ```json
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "foreground": "p:black",
          "background": "p:yellow",
          "template": " \uea83 {{ path .Path .Location }} ",
          "properties": {
            "style": "folder",
		  "max_width": 10
          }
        },
  ```
  
</details>

Perhaps there is something I can do in the template for this? Sorry, I am still new.

**Comment by JanDeDobbeleer** [comment, marked as answer]
@Adam-Kay You can do this using the template function `trunc` or `abbrev` from sprig's [string functions](http://masterminds.github.io/sprig/strings.html).

**Reply by Artemis-Hound** [reply]
This is perfect, thank you!

For anyone else who stumbles upon this, I used [`abbrev`](https://masterminds.github.io/sprig/strings.html#:~:text=abbrev) and changed my template line to: 
```json
"template": " \uea83 {{ path (abbrev 30 .Path) .Location }} ",
```
which will ensure the folder name can only reach a maximum of 30 characters, including the `...` .

**Reply by arledesma** [reply]
I ended up with this segment to keep the prefix and last directory with the beginning trimmed if it exceeds `$max`, otherwise just present the entire path:

```
  - options:
      style: full
    template: >-
        {{ $max := 30 }}{{ if le (len .Path) $max }}{{ path .Path .Location }}{{ else }}{{ $p := replace "\\" "/" .Path }}{{ $s := splitList "/" $p }}{{ $root := first $s }}{{ $tail := last $s }}{{ $budget := int (sub $max (add (len $root) 5)) }}{{ if le (len $tail) $budget }}{{ $root }}/.../{{ $tail }}{{ else }}{{ $avail := int (sub $max (add (len $root) 4)) }}{{ $root }}/...{{ trunc (int (mul -1 $avail)) $tail }}{{ end }}{{ end }}
    foreground: "#dddddd"
    powerline_symbol: 
    background: "#0000ff"
    type: path
    style: powerline
```

<img width="1236" height="42" alt="image" src="https://github.com/user-attachments/assets/275a03eb-3312-40a7-a032-716587be68d1" />
<img width="1235" height="57" alt="image" src="https://github.com/user-attachments/assets/35992ecd-2d1b-4d4b-95f9-2e7479fb7952" />

Maybe there is a more elegant solution for this, or maybe a new template function could help.
