### DISCUSSION TITLE
New line between transient prompt and prompt?

### DISCUSSION THREAD

**Discussion by bragur** [JanDeDobbeleer/oh-my-posh#5034] [Troubleshoot] [answered]
What's the best way to achieve this?
<img src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/9976688/7ec0dc22-4989-4f44-a22c-b6e9c8be001d" width="200px" />

I'm currently trying to add `newline = true` to my initial path block segment, which works fine in existing terminals but when I spawn a new terminal it will add a newline at the top and enter characters into my prompt:
<img src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/9976688/32e9cf60-8755-41aa-88f6-1bed882132e8" width="200px" />

Example config:
```toml
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'
    template = '  {{ path .Path .Location }} '

  [blocks.segments.properties]
    style = 'folder'

[transient_prompt]
  foreground = "green"
  background = 'transparent'
  template = "{{ .Folder }} ❯ "

```

Running zsh `5.9` and Wezterm `20240203-110809-5046fc22`
