### DISCUSSION TITLE
Conditional powerline/diamond symbols

### DISCUSSION THREAD

**Discussion by N8WM** [JanDeDobbeleer/oh-my-posh#5045] [Ideas]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What would you like to see added?

It would be amazing if there was a way to apply segment symbols conditionally based on where they are in the block. Maybe there could be two additional segment properties for powerline-type and/or diamond-type segments (perhaps called "block_start_symbol" and "block_end_symbol") which conditionally take effect when the segment is at the beginning or end of a block. For example, I have a varying number of segments on my rightmost block:
<img width="1512" alt="Screenshot 2024-06-10 at 6 30 58 PM" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/29682192/cab1d5f0-5a73-4779-9bba-13263be19769">
<img width="1512" alt="Screenshot 2024-06-10 at 6 31 23 PM" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/29682192/64023ac5-145a-4f0e-9721-03eae3a9eb40">
I would prefer to be able to configure my start and end symbols of the segments to look like this when they are at the edge of a block:
<img width="1512" alt="Screenshot 2024-06-10 at 6 33 24 PM" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/29682192/39d60221-c573-45d7-b090-6601804d5cf4">

**Comment by JanDeDobbeleer** [comment]
@N8WM pretty sure this can already be achieved today. Can you share your configuration so I can have a quick look?

**Reply by N8WM** [reply]
Oh thanks for the quick response. Here is the basic config I have come up with so far, optimally I would want rounded or flat edges for both blocks instead of the powerline symbol.

```toml
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
iterm_features = ['current_dir', 'remote_host']
shell_integration = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    foreground = 'transparent'
    background = 'default'
    powerline_symbol = ''
    template = ' {{ if .WSL }}WSL {{ end }}{{ .Icon }} '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    foreground = 'transparent'
    background = 'yellow' 
    powerline_symbol = ''
    template = '{{ if .SSHSession }} 󰢹 {{ .UserName }} {{ end }}'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    foreground = 'transparent'
    background = 'blue'
    powerline_symbol = ''
    template = '  {{ .Path }}{{ if not .Writable }} {{ end }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    foreground = 'transparent'
    background = 'green'
    powerline_symbol = ''
    template = ' 󰄉 {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'round'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  newline = false

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    foreground = 'transparent'
    background = 'yellow'
    powerline_symbol = ''
    invert_powerline = true
    template = '{{ if .Error }}{{ .Error }}{{ else }}  {{ if .Venv }}{{ .Venv }}{{ else }}{{ .Full }}{{ end }} {{ end }}'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    foreground = 'transparent'
    background = 'green'
    powerline_symbol = ''
    invert_powerline = true
  

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}lightGreen{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}darkGray{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'darkGray'
  background = 'transparent'
  template = '❯❯ '
```
Note that both blocks will have a varying number of segments and what I want is for the end segments to have their edge symbol updated accordingly
