### DISCUSSION TITLE
The git segment looks a bit funky...

### DISCUSSION THREAD

**Discussion by aroyx** [JanDeDobbeleer/oh-my-posh#5155] [Troubleshoot] [answered]
I have this git segment that shows weird looking git project version. Like for example this what in looks like when I cd to rustlings dir version 5.6.1. 
![2024-06-23_21-59](https://github.com/JanDeDobbeleer/oh-my-posh/assets/128731129/8347f5ee-aefa-46fd-8d38-30b2ddb8dcc9)

this is the template part:
```toml
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
```
and this is the whole segment: 

```toml
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'magenta'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

```
