### DISCUSSION TITLE
Empty Row above the first prompt after update

### DISCUSSION THREAD

**Discussion by sanjeev-singh-2311** [JanDeDobbeleer/oh-my-posh#5247] [Troubleshoot] [answered]
I have been using oh-my-posh for quite some time and so far it worked really nice for me.
After updating to `v21.23.1`  a blank row appears on top of my prompt every time I run `clear` or `reset`

I thought this was a normal behaviour but the documentation says 

`Start the block on a new line - defaults to false. For bash, zsh, pwsh and cmd this will not print a newline that's defined on the first block when the prompt is on the first line (when using clear), or when the shell session starts (1st prompt).`

I'm using `zsh 5.9` on `alacritty 0.13.2` 

This is how it used to be on `v21.21.0` (No empty row above first prompt after running `clear`)
![OLD_VERSION_NO_EMPTY_ROW](https://github.com/JanDeDobbeleer/oh-my-posh/assets/84013653/4d3dbe22-c7c4-46c7-ac67-5d35268a7377)

And this is how it is after the update (Empty row appears after running `clear`)
![NEW_VERSION_EMPTY_ROW](https://github.com/JanDeDobbeleer/oh-my-posh/assets/84013653/d0022ea8-edc9-4ef0-a6c9-6d9a03b68d40)

I tried to manually install the binaries of different versions from the release section and I find that this behaviour is happening  after `v21.21.1`

My prompt configuration
```toml
version = 2
final_space = true
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
  type = 'path'
  style = 'plain'
  background = 'transparent'
  foreground = 'p:terminal-magenta'
  template = "{{.Path }}"

  [blocks.segments.properties]
  style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:pastal-grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}<cyan></cyan>{{ end }}{{ if gt .Behind 0 }}<cyan></cyan>{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:terminal-yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 5000


  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:pistachio-green'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'php'
    style = 'plain'
    foreground = 'p:terminal-blue'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:terminal-yellow'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'julia'
    style = 'plain'
    foreground = 'p:terminal-magenta'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'ruby'
    style = 'plain'
    foreground = 'p:terminal-red'
    template = ' {{ .Full}} '

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:light-sky-blue'
    template = 'ﳑ {{ .Full}} '

  [[blocks.segments]]
    type = 'command'
    style = 'plain'
    foreground = 'p:white-blue'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'zsh'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{ if gt .Code 0 }}p:terminal-red{{ end }}",
      "{{ if eq .Code 0 }}p:light-sky-blue{{ end }}",
    ]
    template = ''

[transient_prompt]
    foreground_templates = [
      "{{ if gt .Code 0 }}p:terminal-red{{ end }}",
      "{{ if eq .Code 0 }}p:light-sky-blue{{ end }}",
    ]
  background = 'transparent'
  template = ' '

[secondary_prompt]
  foreground = 'p:light-sky-blue'
  background = 'transparent'
  template = ' '

```
