### DISCUSSION TITLE
Use Angle brackets in git segment template

### DISCUSSION THREAD

**Discussion by rmiller3** [JanDeDobbeleer/oh-my-posh#5568] [Troubleshoot] [answered]
My desired git segment is just the branch name in angle brackets; a simple one that doesn't require a nerd font (disregard how the triple equals renders in github)
```
< branchname ≢ >
```
I got it working, more or less, with this modification of one of the default themes.  However, if I replace 'xx' below with '<' and 'yy' with '>' it breaks it and doesn't render the segment.  How can I properly escape the angle brackets?  If I use square brackets it works, if I leave it 'xx' and 'yy' it works (renders that)
```
  - type: git
    style: plain
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}"
    - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
    - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
    template: "xx{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}xx"
    properties:
      branch_max_length: 25.0
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
      branch_icon: ''
      upstream_icon: ''
      azure_devops_icon: ''
```
