### DISCUSSION TITLE
Catppuccin Mocha theme based on the default

### DISCUSSION THREAD

**Discussion by pkazmier** [JanDeDobbeleer/oh-my-posh#5578] [Themes]
So I spent all morning tweaking the default oh-my-posh theme with the Catppuccin Mocha color palette. I really like the included theme in oh-my-posh, but the colors weren't compatible with my beloved Catppuccin. Here is the outcome:
<img width="846" alt="Screenshot 2024-09-08 at 9 44 59 AM" src="https://github.com/user-attachments/assets/343261ae-223f-4332-af7c-e2daf49c3e94">

And here is my configuration for anyone that wants to tune/tweak:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  base: "#1e1e2e"
  black: "#000000"
  blue: "#89b4fa"
  crust: "#11111b"
  flamingo: "#f2cdcd"
  green: "#a6e3a1"
  lavender: "#b4befe"
  mantle: "#181825"
  maroon: "#eba0ac"
  mauve: "#cba6f7"
  overlay0: "#6c7086"
  overlay1: "#7f849c"
  overlay2: "#9399b2"
  peach: "#fab387"
  pink: "#f5c2e7"
  red: "#f38ba8"
  rosewater: "#f5e0dc"
  sapphire: "#74c7ec"
  sky: "#89dceb"
  subtext0: "#a6adc8"
  subtext1: "#bac2de"
  surface0: "#313244"
  surface1: "#45475a"
  surface2: "#585b70"
  teal: "#94e2d5"
  text: "#cdd6f4"
  yellow: "#f9e2af"
secondary_prompt:
  template: "<p:yellow,transparent>\ue0b6</><,p:yellow> > </><p:yellow,transparent>\ue0b0</> "
  foreground: p:black
  background: transparent
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    leading_diamond: 
    trailing_diamond: 
    template: " {{ if .SSHSession }}\ueba9 {{ end }}{{ .UserName }} "
    foreground: p:black
    background: p:mauve
    type: session
    style: diamond
  - properties:
      cache_duration: none
      style: folder
    template: " \uea83 {{ path .Path .Location }} "
    foreground: p:black
    powerline_symbol: 
    background: p:sapphire
    type: path
    style: powerline
  - properties:
      branch_max_length: 25
      cache_duration: none
      fetch_status: true
      fetch_upstream_icon: true
    template: " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} "
    foreground: p:black
    powerline_symbol: 
    background: p:green
    type: git
    style: powerline
    foreground_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:black{{ end }}"
    - "{{ if gt .Ahead 0 }}p:black{{ end }}"
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}p:peach{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}"
    - "{{ if gt .Ahead 0 }}p:lavender{{ end }}"
    - "{{ if gt .Behind 0 }}p:maroon{{ end }}"
  - properties:
      cache_duration: none
    template: " \uf0e7 "
    foreground: p:red
    powerline_symbol: 
    background: p:surface1
    type: root
    style: powerline
  newline: true
- type: prompt
  alignment: left
  leading_diamond: <transparent,background></>
  trailing_diamond: 
  segments:
  - properties:
      cache_duration: none
      style: round
      threshold: 1500
    trailing_diamond: 
    foreground: p:sapphire
    background: p:surface1
    type: executiontime
    style: diamond
  - properties:
      always_enabled: true
      cache_duration: none
    template: " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} "
    foreground: p:black
    background: p:blue
    type: status
    style: diamond
    background_templates:
    - "{{ if gt .Code 0 }}p:red{{ end }}"
- type: rprompt
  segments:
  - properties:
      cache_duration: none
      display_mode: files
      fetch_package_manager: false
      home_enabled: false
    template: "\ue718 "
    foreground: p:green
    background: transparent
    type: node
    style: plain
  - properties:
      cache_duration: none
      fetch_version: false
    template: "\ue626 "
    foreground: p:sapphire
    background: transparent
    type: go
    style: plain
  - properties:
      cache_duration: none
      display_mode: files
      fetch_version: false
      fetch_virtual_env: true
      home_enabled: false
    template: "{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}\ue235 {{ .Venv }} {{ end }}{{ end }}"
    foreground: p:yellow
    background: transparent
    type: python
    style: plain
  - properties:
      cache_duration: none
    template: "in <p:blue><b>{{ .Name }}</b></> "
    foreground: p:overlay1
    background: transparent
    type: shell
    style: plain
  - properties:
      cache_duration: none
    template: at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>
    foreground: p:overlay1
    background: transparent
    type: time
    style: plain
tooltips:
- properties:
    display_default: true
  leading_diamond: 
  trailing_diamond: 
  template: " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
  foreground: p:text
  background: p:peach
  type: aws
  style: diamond
  tips:
  - aws
- properties:
    display_default: true
  leading_diamond: 
  trailing_diamond: 
  template: " \uebd8 {{ .Name }} "
  foreground: p:text
  background: p:sapphire
  type: az
  style: diamond
  tips:
  - az
version: 3
final_space: true
```
