### DISCUSSION TITLE
Upgrade to 24 breaks leading_diamond in top-level block?

### DISCUSSION THREAD

**Discussion by pkazmier** [JanDeDobbeleer/oh-my-posh#5911] [Troubleshoot] [answered]
After upgrading to 24, my [prompt](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/5578) stopped working. Specifically, it appears that `leading_diamond` is not working as I expect. I use this feature to ensure my block always starts with a specific symbol regardless of whether or not which segment may be enabled. I've reviewed the release notes and poked around other issues, but have not found my answer. I've distilled this down to a very small config for testing purposes:

```yaml
version: 3
final_space: true
blocks:
- type: prompt
  alignment: left
  leading_diamond: <transparent,background></>
  trailing_diamond: 
  segments:
  - type: executiontime
    properties:
      style: round
      threshold: 1500
    trailing_diamond: 
    foreground: p:sapphire
    background: p:surface1
    style: diamond
  - type: status
    properties:
      always_enabled: true
    foreground: p:black
    background: p:blue
    style: diamond
    template: " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} "

palette:
  sapphire:  "#74c7ec"
  blue:      "#89b4fa"
  surface1:  "#45475a"
  black:     "#000000"
```

With this config, version 23.20.3 works correctly and looks like this: (note the first character of the prompt):
<img width="775" alt="image" src="https://github.com/user-attachments/assets/dc5ad0af-27f4-47d6-80a2-746c65227233">

When I upgrade to 24, the leading diamond no longer shows unless the exectime segment is enabled:
<img width="775" alt="image" src="https://github.com/user-attachments/assets/10d1dfb9-ebf6-410a-87b6-a4c663fd4b0f">

I'm sure this is user error and documented somewhere, but I reread the docs for the block section and leading diamond parameter, but I must be missing something. Any help would be appreciated. Thank you.
