### DISCUSSION TITLE
`enable_cursor_positioning` doesn't seem to take any effect

### DISCUSSION THREAD

**Discussion by shumvgolove** [JanDeDobbeleer/oh-my-posh#6058] [Troubleshoot]
Hello there!

[The docs](https://ohmyposh.dev/docs/configuration/general#settings) mention that:

> `enable_cursor_positioning` enable fetching the cursor position in bash and zsh to allow automatic hiding of leading newlines when at the top of the shell

Unfortunately, enabling that option doesn't seem to take any effect: extra newline is still printed. I've read the following issues with the similar problem:

- #5703
- #5732 

...but I'm a little confused: is it a limitation of `zsh` as pointed in #5703, or does  `enable_cursor_positioning` suppose to fix the issue? Thanks in advance.

---

### Environment

- **os**: `Linux`
- **zsh**: `5.9`
- **oh-my-posh**: `v24.17.1`

### Steps to reproduce

1. Create the following config:

     ```sh
     nvim 1.toml
     ```

     ```toml
     version = 3
     shell_integration = true
     enable_cursor_positioning = true
     final_space = true

     [[blocks]]
       type = 'prompt'
       alignment = 'left'
       newline = true

       [[blocks.segments]]
         template = '{{ .Path }}'
         foreground = 'yellow'
         background = 'transparent'
         type = 'path'
         style = 'plain'

         [blocks.segments.properties]
           cache_duration = 'none'
           style = 'full'

     [[blocks]]
       type = 'prompt'
       alignment = 'left'
       newline = true

       [[blocks.segments]]
         template = '❯'
         background = 'transparent'
         type = 'text'
         style = 'plain'
         foreground_templates = ['{{if eq .Code 0}}green{{else}}red{{end}}']

         [blocks.segments.properties]
           cache_duration = 'none'
     ```

2. Launch clean zsh:

     ```sh
     zsh -dfi
     ```

3. Init oh-my-posh:

    ```sh
    eval "$(ohmyposh init zsh --config 1.toml)"
    ```

4. Clear the screen once with `Ctrl+L`.

5. Execute anything (e.g. `whoami` like in an original issue).

6. Clear the screen again with `Ctrl+L` and observe that extra line is added even with `enable_cursor_positioning = true`.
