### DISCUSSION TITLE
Conditional variables ?

### DISCUSSION THREAD

**Discussion by filviu** [JanDeDobbeleer/oh-my-posh#6372] [Troubleshoot] [answered]
Hi,

Just discovered oh-my-posh and I'm in the process of migrating my starship config to better be able to evaluate it. I'm stuck replicating the following starship bit:

```toml
[username.aliases]
"myusername" = ""
root = "󰇴"

[hostname.aliases]
somelongstring = "short_hostname"
```

I searched and I couldn't find aliases like this so next I tried:

```yaml
var:
  user_alias: {{if eq .UserName "myusername"}}foo{{else}}{{.UserName}}{{end}}
```

But the above doesn't seem to work. Is there a way to acomplish what I'm trying without adding the same ifs at each step the username is used (title bar, prompt, etc)
