### DISCUSSION TITLE
Can not get Bun version

### DISCUSSION THREAD

**Discussion by Fred-Vatin** [JanDeDobbeleer/oh-my-posh#6563] [Troubleshoot]
Hi,

Using oh-my-posh v.26.11.0 when I used `type = "node"`, it displays the bun icon:
```toml
[[blocks]]
type = "rprompt"

[[blocks.segments]]
leading_diamond = ""
trailing_diamond = ""
template = """\
 \
{{ if .PackageManagerIcon }}\
  {{ .PackageManagerIcon }}\
{{ end }}\
{{ if .Full }} \
  {{ .Full }}\
{{ end }} \
"""
foreground = "p:node-foreground"
background = "p:node-background"
type = "node"
style = "diamond"

[blocks.segments.properties]
fetch_package_manager = true
fetch_version = true
```
I get
![image](https://github.com/user-attachments/assets/1cf644dd-e1c8-4601-8301-5cb57b358e1e)

---
### Edit
If I use the same code with `type = "bun"`, I need to remove `{{ .PackageManagerIcon }}` and use the icon from nerd font. Else I get `unable to create text based on template`.

This works with bun:
```toml
[[blocks]]
type = "rprompt"

[[blocks.segments]]
leading_diamond = ""
trailing_diamond = ""
template = "  {{ .Full }}"
foreground = "p:node-foreground"
background = "p:node-background"
type = "bun"
style = "diamond"

[blocks.segments.properties]
fetch_version = true
```
![image](https://github.com/user-attachments/assets/86fdac5f-01b9-431c-8eb0-8ee98c46bdac)
