### DISCUSSION TITLE
Are multiple background colors--usable by Powerline/Diamond segment styles--possible?

### DISCUSSION THREAD

**Discussion by ninjack-dev** [JanDeDobbeleer/oh-my-posh#6568] [Troubleshoot]
I've been chipping away at a segment which displays the current shell's parents:
 ![image](https://github.com/user-attachments/assets/1e4f5b4b-519c-4ea0-8bb1-98d9f5baf35f)
```yaml
      - type: command
        style: diamond
        trailing_diamond: "\u200B" # Ugh
        properties:
          script: "~/.config/ohmyposh/shelllist.sh"
        template: 
          "\
          {{ $Var := .Var }}\
          {{ $First := first (splitList \" \" .Output) }}\
          {{ index $Var $First }}\
          <p:{{ $First }}>\
          {{ $Prev := $First }}\
          {{ range rest (splitList \" \" .Output) }}\
          <,p:{{.}}><b>{{ if (eq $Prev .) }}<p:trueblack></>{{ else }}{{ end }}</b></></>\
          <p:black,p:{{.}}>{{ index $Var . }}</>\
          {{ $Prev = . }}\
          <p:{{.}}>\
          {{ end }}<,transparent></></>"
        background_templates:
          - "p:{{ first (splitList \" \" .Output) }}"
        foreground: p:black
        cache:
          strategy: session
```
It works pretty well, but the only way I was able to get it working in its current form was:
1) set the background color of the segment to the 
2) manually append what would normally be the `trailing_diamond`
3) replace the `trailing_diamond` with a zero-width character (thus the "Ugh") to avoid a large gap between this and the subsequent Powerline segment
As you can see, this causes the segment to be unable to merge with the next Powerline segment; if I allowed it to, it would use the background color of the root shell. 

This works ok, but I was wondering if there are shenanigans I could pull to get this segment to cleanly merge with the both the previous/subsequent Powerline/Diamond segments. The only "solution" I've really come up with thus far is to duplicate this config into a temp file at runtime and dynamically modify it when an OMP session starts, using `yq`/`jq` to insert Powerline segments; that would be quite complicated, and I think I can live with a gap if it was the only option.

I have zero expectations for whether it's possible, so no worries there. If it would at least by *theoretically* possible by getting at the Go code, I'd be happy to take a shot at a custom segment, if there's any community interest.
## Extra Context
**Shell Tree Script**:
```sh
#!/bin/sh
ps -o pid=,ppid=,comm= \
  | awk -v pid=$$ -v shell="$POSH_SHELL" '
BEGIN { 
  chain = ""
  bash_subshells = 2 # Bash spawns a couple of subshells for the OMP integration
  zsh_subshells = 1  # Zsh only spawns one
}
{
    proc[$1] = $2
    comm[$1] = $3
}
END {
    p = pid
    shubshell_factor = 0
    skip_two = 0     # Skip the invocation of oh-my-posh and this script
    while (comm[p] != "" && !seen[p]) {
        if (shell == "zsh" && comm[p] == "zsh" && subshell_factor < zsh_subshells) {
           subshell_factor++
        }
        else if (shell == "bash" && comm[p] == "bash" && subshell_factor < bash_subshells) {
           subshell_factor++
        } else if (skip_two++ >= 2){
           chain = comm[p] (chain ? " " chain : "")
        }
        seen[p] = 1
        p = proc[p]
    }
    print chain
}'
```
**Variables/Colors:**
```yaml
var:
  bash: "  "
  zsh: " % "
  pwsh: "  "
  fish: "  "
  nu: "  "

palette:
  black: "#262B44"
  trueblack: "#000000"
  blue: "#4B95E9"
  green: "#59C9A5"
  orange: "#F07623"
  red: "#D81E5B"
  white: "#E0DEF4"
  yellow: "#F3AE35"

  bash: "#45B052"
  zsh: "#F15A1F" # Color pulled from https://en.wikipedia.org/wiki/Z_shell#/media/File:Z_Shell_Logo_Color_Vertical.svg
  pwsh: "#0078D4" # Color pulled from https://learn.microsoft.com/en-us/powershell/
  fish: "#4A9CC9"
  nu: "#3DD68C"
```
