### DISCUSSION TITLE
Remove spaces between segments

### DISCUSSION THREAD

**Discussion by JustinGrote** [JanDeDobbeleer/oh-my-posh#858] [Troubleshoot] [answered]
Given this config:
```
- type: prompt
  alignment: left
  newline: true
  segments:
  - type: root
    properties:
      root_icon: ⚡
    style: plain
    foreground: '#E06C75'
  - type: exit
    properties:
      display_exit_code: false
      prefix: x
    style: plain
    foreground: '#C94A16'

  - type: text
    properties:
      prefix: ''
      text: ❯
    style: plain
    foreground: '#63F08C'


```

I want this:
![image](https://user-images.githubusercontent.com/15258962/126055159-a86e41ba-a3f6-476b-91ef-15d3033f2136.png)

To not have a space before the lightning bolt and after it. Is there a config setting I am missing?
