### ISSUE TITLE
Right prompt gets deleted when using backspace

### ISSUE THREAD

**Issue by emilyyyylime** [JanDeDobbeleer/oh-my-posh#2946]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

**Description:**
I have a right prompt configured with Oh My Posh on bash, when editing the command in the prompt (specifically when deleting characters) some weird behaviour insues

**Steps to reproduce:**
Configure kitty to use the minimal config from below
Write something
Press backspace
Right prompt disappears!

*note:* if you press backspace in the middle of the command instead of the right prompt entirely disappearing, it just moves left (which still isn't expected behaviour)

**Screenshots**
![image](https://user-images.githubusercontent.com/40892795/195977390-14188b57-20a9-48a3-91af-195bbbcb7cb2.png)
![image](https://user-images.githubusercontent.com/40892795/195977406-cf8aab44-cc61-4752-acc0-91d4cd55203e.png)

### Theme

minimal theme to reproduce:
```
blocks:
  - alignment: right
    segments:
      - type: text
        style: plain
        template: blah blah
    type: rprompt
version: 2
```

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
This doesn't seem relevant to me
```
