### ISSUE TITLE
[Segment request] Sudo status

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3562]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be nice to have a segment that shows the sudo unlock status. I made an implementation of this for my personal config, though my implementation isn't the best since it blocks the prompt for a bit (between 250-500ms in my testing). Regardless, here's what it looks like for me (implemented as a tooltip for sudo):
![Screenshot 2023-03-07 at 10 30 18](https://user-images.githubusercontent.com/14863373/223487147-0631a9d3-5c3f-4dbd-bbd7-fb7dfa228e3f.png)

<details>

<summary>
My code
</summary>

```yaml
tooltips:
    - type: command
      tips:
          - sudo
      style: diamond
      leading_diamond: 
      properties:
          shell: bash
          command: 'sudo -n true && echo true || echo false'
      background_templates:
          - '{{ if eq .Output "true" }}green{{ else }}red{{ end }}'
      foreground_templates:
          - '{{ if eq .Output "true" }}black{{ else }}lightWhite{{ end }}'
      template: ' {{ if eq .Output "true" }}{{else}}{{end}} SUDO '
```

</details>

One way that users might find this useful is to have it always shown whenever sudo is unlocked. It could also just be used as a tooltip like I currently have it implemented.

**Comment by JanDeDobbeleer** [comment]
@asportnoy out of curiosity, why doesn't the `session` segment work using the `.Root` property?

**Comment by asportnoy** [comment]
@JanDeDobbeleer Just tried that, doesn't show any difference when sudo is unlocked. From reading the docs, my understanding is that would only be true if the entire session is run as root which is not case here. The shell is still under my account (which is not root). Sudo showing as "unlocked" just means that sudo will not require my password because I recently entered it.

**Comment by JanDeDobbeleer** [comment]
@asportnoy I will have a look at how to extend this so that both cases apply. Or add an additional `.Sudo` property specifically for this.

**Comment by JanDeDobbeleer** [comment]
@asportnoy I have no idea how to get this information from golang without an additional process (I tried a lot of things), so my proposal would be to use the [context functions](https://ohmyposh.dev/docs/configuration/templates#environment-variables) rather than a command segment, that way the command is executed in the shell, which should be rather fast. To achieve this, add the following to `.bashrc` after initialising oh-my-posh:

```bash
function set_poshcontext() {
    sudo -n true && export SUDO_USER=true || export SUDO_USER=false
}
```

You can then use a text segment to display this:

```yaml
tooltips:
    - type: text
      tips:
          - sudo
      style: diamond
      leading_diamond: 
      background_templates:
          - '{{ if eq .Env.SUDO_USER "true" }}green{{ else }}red{{ end }}'
      foreground_templates:
          - '{{ if eq .Env.SUDO_USER "true" }}black{{ else }}lightWhite{{ end }}'
      template: ' {{ if eq .Env.SUDO_USER "true" }}{{else}}{{end}} SUDO '
```
