### ISSUE TITLE
Execution time threshold being ignored

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3591]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have my execution time threshold set to 1000ms, but the segment is showing even if the execution time is less than that
<img width="1512" alt="Screenshot 2023-03-15 at 12 02 20" src="https://user-images.githubusercontent.com/14863373/225385416-0a1f89fa-b870-4c40-a62e-824f4cc7e036.png">

### Theme

https://gist.github.com/asportnoy/88e8ffcf35ad95dd16a04cf284b86fab

Relevant segment:
```yaml
- type: executiontime
  background: yellow
  foreground: black
  style: diamond
  leading_diamond: '<background,parentBackground></>'
  properties:
    threshold: 1000
    style: round
  template: '  {{ .FormattedMs }} '
```

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```Shell
https://gist.github.com/asportnoy/628565646fad3def04df685f19b6f6cc
```
