### ISSUE TITLE
Add option powerline_skipLeadingIfFirst to skip the leading symbol if it is the first item in the line

### ISSUE THREAD

**Issue by JustinGrote** [JanDeDobbeleer/oh-my-posh#3623]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

```
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: session
        style: powerline
        background: "#569CD6"
        foreground: "#333333"
        template: "{{ if .SSHSession }}🖥️ {{ .UserName }}@{{ .HostName }}{{ end }}"
      - type: path
        style: powerline
        powerline_symbol: 
        powerline_skipLeadingIfFirst: true
        background: "#333333"
        template: "{{ .Path }}"
```

Expected:
![image](https://user-images.githubusercontent.com/15258962/227417035-781c9701-906a-42ff-a3ca-c1cff44683fb.png)

If the first segment session is not rendered (shows as false in the print debug), then the next segment should basically take on the shape of "diamond" with trailing_diamond set to the powerline character and no leading_diamond. The code I used to make the above is as follows:
```
      - type: path
        style: diamond
        trailing_diamond: 
        background: "#333333"
        template: "{{ .Path }}"
```

If there is something there, then it should behave like powerline as normal

Actual:
![image](https://user-images.githubusercontent.com/15258962/227417096-988623e9-077b-4489-9a10-45c126dfbabc.png)

**Comment by JanDeDobbeleer** [comment]
@JustinGrote when #3627 lands, you can do this:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

accent_color: "32"
blocks:
- alignment: left
  segments:
  - background: "#569CD6"
    foreground: "#333333"
    style: diamond
    template: " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }}@{{ .HostName }} "
    trailing_diamond: "\ue0b4"
    type: session
  - background: "#ffffff"
    foreground: "#111111"
    style: diamond
    template:  " {{ .Path }} "
    trailing_diamond: "\ue0b4"
    type: path
  type: prompt
final_space: true
version: 2.0
```
