### ISSUE TITLE
Only print newline when block (line?) above is not empty

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#4182]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently adding `newline: true` always prints a newline. If you got a block you'd like to separate and it's empty, you basically get 2 empty lines for each new input line.

Would be nice if there was a way to make the newline conditional if previous template outputs anything. E.g. `newline: if_previous_not_empty` or `newline_mode: if_previous_not_empty` or anything alike.

**Comment by JanDeDobbeleer** [comment]
@Destroy666x I think this can always be the case. Don't see why anyone would purposefully want two newlines when specifying only one.

**Comment by Destroy666x** [comment]
Unfortunately still getting double blank lines on 18.6.0 @JanDeDobbeleer 

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/3606072/f111757c-373b-4e5b-bdf4-2be6564a5d6e)

My whole config just in case it helps:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2
final_space: false
accent_color: red
console_title_template: "{{ if .Root }}+{{ end }}{{ .Shell }}: {{ .PWD }} ({{ .UserName }}@{{ .HostName }})"

palettes:
  template: accent_dark
  list:
    accent_dark:
      success: green
      info: cyan
      error: red
      warning: yellow
      icon: accent
      url: magenta
      datetime: blue
    simple_dark:
      success: green
      info: white
      error: red
      warning: yellow
      icon: white
      url: magenta
      datetime: white

var:
  GitCommitMaxLength: 40
  GitCommitDateFormat: "2 Jan, 15:04"
  # TODO replace back once I set up languages
  VersionOrError: "{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: git
        style: plain
        template: "<p:url><b>{{ url .UpstreamIcon .UpstreamURL }}</b></><p:icon>{{ if .IsBare }} \U000F0F52{{ end }}{{ if .IsWorkTree }} \U000F0645{{ .WorktreeCount }}{{ end }}</>
{{ .HEAD }}<b>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}
{{ if .Working.Changed }} <p:icon>\U000F1323</> {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} <p:icon>\U000F042F</> {{ .Staging.String }}{{ end }}{{ if .StashCount }} \U000F0194{{ .StashCount }}{{ end }}</b>
<p:icon>\U000F1173</> {{ trim (trunc .Var.GitCommitMaxLength .Commit.Subject) }}{{ if gt (len .Commit.Subject) .Var.GitCommitMaxLength }}...{{ end }}
<p:datetime>{{ date .Var.GitCommitDateFormat .Commit.Timestamp }}</>"
        properties:
          branch_max_length: 30
          fetch_bare_info: true
          fetch_status: true
          fetch_upstream_icon: true
          truncate_symbol: ...
          status_formats:
            Added: "<p:icon>\U000F0415</>%d"
            Deleted: "<p:icon>\U000F0415</>%d"
            Modified: "<p:icon>\U000F0992</>%d"
            Unmerged: "<p:icon>x</>%d"
            Untracked: "<p:icon>\U000F0209</>%d"
          branch_ahead_icon: "<p:icon>\u21B1</>"
          branch_behind_icon: "<p:icon>\u21B2</>"
          branch_gone_icon: "<p:icon>\uEABD</>"
          branch_icon: "<p:icon>\uE725</> "
          branch_identical_icon: "<p:icon>\uF44E</>"
          cherry_pick_icon: "<p:icon>\U000F1042</>"
          commit_icon: "<p:icon>\uF417</>"
          git_icon: "\uE702"
          merge_icon: "<p:icon>\uE727</>"
          no_commits_icon: "<p:icon>\U000F0394</>"
          rebase_icon: "<p:icon>\uEBAB</>"
          revert_icon: "<p:icon>\uF0E2</>"
          tag_icon: "<p:icon>\uF02B</>"

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: time
        style: plain
        foreground: "p:datetime"
        template: "<p:icon>\U000F0954</> {{ date .Format .CurrentDate }} "
        properties:
          time_format: "15:04:05"
      - type: root
        style: plain
        foreground: "p:icon"
        template: "\U000F0017 "
      - type: path
        style: plain
        foreground: "p:info"
        template: "{{ path .Path .Location }} "
        properties:
          mapped_locations:
            "~": "\U000F024C"
            "~/Desktop": "\U000F09E8"
            "C:/Windows": "\uF17A"
            "D:/Backups": "\U000F0D0B"
            "D:/Backups/Data/Office": "\U000F19F6"
            "D:/Backups/Data/Media/Music": "\U000F1359"
            "D:/Backups/Data/Media/Photos": "\U000F024F"
            "D:/Backups/Data/Media/Videos": "\U000F19FA"
            "D:/Dev/Repositories/git": "\U000F0CCF"
            "D:/Games": "\uF11B"
            "D:/Temporary": "\U000F0252"
          style: agnoster_full
      # - type: svn
        # style: plain
        # template: "<p:icon>\U000F062C</> {{ .Branch }} rev {{ .BaseRev }} {{ .Working.String }} "
        # properties:
          # fetch_status: true
      # - type: php
        # style: plain
        # template: "<p:icon>\U000F031F</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: python
        # style: plain
        # template: "<p:icon>\uE235</> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
        # properties:
          # home_enabled: true
      # - type: node
        # style: plain
        # template: "<p:icon>\U000F011B</> {{ if .Error }}{{ .Error }}{{ else }}{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}{{ end }} "
        # properties:
          # fetch_package_manager: true
          # home_enabled: true
          # npm_icon: "\uE71E"
          # yarn_icon: "\uF61A"
      # - type: dart
        # style: plain
        # template: "<p:icon>\uE798</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: flutter
        # style: plain
        # template: "<p:icon>\uE798</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: lua
        # style: plain
        # template: "<p:icon>\uE620</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: dotnet
        # style: plain
        # template: "<p:icon>\uE256</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: java
        # style: plain
        # template: "<p:icon>\uE256</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: ruby
        # style: plain
        # template: "<p:icon>\uE791</> {{ .Var.VersionOrError }} "
        # properties:
          # home_enabled: true
      # - type: aws
        # style: plain
        # template: "<p:icon>\uE7AD</> {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
      # - type: kubectl
        # style: plain
        # template: "<p:icon>\U000F0833</> {{ .Context }}{{ if .Namespace }}{{ .Namespace }}{{ else }}default{{ end }} "
      - type: project
        style: plain
        template: "<p:icon>\uEB99</> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }}{{ if .Name }}{{ .Name }} {{ end }}{{.Version}}{{ end }}{{ end }} "
      # - type: session
      - type: text
        style: plain
        foreground: "p:icon"
        template: "\uF061 "

  - type: rprompt
    alignment: right
    segments:
      - type: executiontime
        style: plain
        properties:
          treshold: 1000
      - type: status
        style: plain
        foreground: "p:error"
        template: "{{ if .Error }}\uEBDE {{ .String }}{{ end }}"
        status_template: "{{ if gt .Code 0 }}{{ reason .Code }}{{ end }}"
```
