### ISSUE TITLE
Integer variables are not too well supported

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#4184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Don't know if more of a bug or feature request/enhancement, but current variables don't support integers too well.

Example:

```
var:
  GitMaxCommitLength: 40

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: git
        style: 
        template: "{{ .HEAD }} {{ trunc .Var.GitMaxCommitLength .Commit.Subject }}{{ if gt (len .Commit.Subject) .Var.GitMaxCommitLength }}...{{ end }}"
```

Results in error:
> wrong type for value; expected int; got uint64

It's because `trunc` strictly expects `int`, changing var there to `40` fixes the issue.

Perhaps integers that aren't too high should be defined as more universal `int`.
