### ISSUE TITLE
DSC 3 Resource for oh-my-posh

### ISSUE THREAD

**Issue by denelon** [JanDeDobbeleer/oh-my-posh#4340]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Suggested new feature or improvement

I'd like to be able to use the [WinGet Configuration](https://learn.microsoft.com/windows/package-manager/configuration/) feature to configure oh-my-posh.

In the future when DSC v3 supports the "export" behavior, this could also be used as a part of the export a configuration scenario.
* https://github.com/microsoft/winget-cli/issues/3274
* https://github.com/PowerShell/DSC/issues/73

### Scenario

I want to set up a new device and have the ability to configure oh-my-posh with WinGet Configure or by selecting the configuration in [Dev Home](https://learn.microsoft.com/windows/dev-home/).

### Additional details

I would expect the Microsoft.WinGet.DSC resource would be used to install oh-my-posh on my machine. Then as a dependency I'd like to be able to use a DSC resource to configure oh-my-posh the way I like it.

<img width="867" alt="oh-my-posh" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/61799811/84b0c278-02fc-4bf0-ba5a-6a870862f209">

**Comment by denelon** [comment]
As soon as we get this working, we should put a [sample configuration at Dev Home](https://aka.ms/dsc.yaml).

**Comment by nopeless** [comment]
This looks like an interesting feature, but I don't see how this can drastically reduce time setting up oh my posh

**Comment by denelon** [comment]
It's not aiming to drastically reduce time. It's more about automating the setup and configuration.

**Comment by nopeless** [comment]
I didn't notice you are the product manager for winget

Good luck with the PR, and thanks for the work 👍

**Comment by JanDeDobbeleer** [comment]
@denelon I've been trying to give this a go and I'm blocked on the first step. Maybe it's something obvious, or there are dependencies I don't have which results in a bad user experience.

Sample configuration file:

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
  configurationVersion: 0.2.0
```

Outcome:

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/2492783/0bfa64e1-8fc5-4b06-b7de-2ad6f87171d6)

**Comment by denelon** [comment]
@JanDeDobbeleer I'm so sorry for a very late reply. I didn't see your reply, and was just checking in.

I wasn't able to repro the problem you encountered.

<img width="867" alt="ohmyposh" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/61799811/c2379ed9-3076-4057-91d0-4db27d87b9d5">

```YAML
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
  configurationVersion: 0.2.0
```
