### ISSUE TITLE
Highlight and always show the current *Git* directory name in `Path`

### ISSUE THREAD

**Issue by stevenxxiu** [JanDeDobbeleer/oh-my-posh#4727]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'm thinking of migrating from *Starship*, as many important issues, like [Powerline prompt · Issue #528 · starship/starship](https://github.com/starship/starship/issues/528), seem rather dead. I also like the *Oh My Posh* feature of conditionally showing a segment based on an environment variable.

One feature I really need, is to highlight the *Git* directory's name in the path, and to always show it, if the path is shortened.

I only found [Oh My Posh: getting whether or not in a Git repo in other segments - Stack Overflow](https://stackoverflow.com/q/77389550), which suggests to me what I want isn't currently possible.

**Comment by rockyoung** [comment]
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/1207971/edd15110-b2d2-43fd-9919-ab67d94f3262)

is this what your want? if yes, then check my segment config:
```json
{
    "type": "path",
    "style": "plain",
    "foreground": "#ff80bb",
    // can also replace the \"\" to any icon unicode string you prefer
    "template": "{{if .Segments.Git.Ref}}<#ff0000>{{.Segments.Git.RepoName}}</>{{.Path | replace .Segments.Git.Dir \"\"}}{{else}}{{.Path}}{{end}}",
    "properties": {
        "style": "full"
    }
},
```

but note the "style" property must be "full" and better not change the "folder_separator" thing, or the `replace` may not effected cause the `.Segments.Git.Dir` may not be the same format as the `.Path` which will lead the replacement to be failed!

the drawback is could not use any built-in styles except for "full", but can only implement them by yourself with [Template Logic](https://ohmyposh.dev/docs/configuration/templates#template-logic) and [Functions](https://ohmyposh.dev/docs/configuration/templates#helper-functions)

**Comment by stevenxxiu** [comment]
If `MB-Lyric/` there is a *Git* repo, then yes.

Although I'd rather not display the full path every time, as it can get rather long.

In my current *Starship* config, I have the path shortened. Ideally I'd want the shortening to focus on the parts before the *Git* repo, if it gets too long. Perhaps it could be implemented with what you linked, but I'm not sure how easy that is.

<https://ohmyposh.dev/docs/segments/path> already has many shortening styles, so surely a native implementation would be a lot simpler.

**Comment by rockyoung** [comment]
yes, the 'MB-Lyric' is a repo using git.

if looking to incorporate this feature internally, it might call for a slew of config options. For instance:
 - the abbreviation strategy for path preceding the repo name.
 - whether to abbreviate lengthy path following the repo name (especially if the directory structure runs deep), and what strategy to employ.
 - we'll likely need a config option for how to highlight repo name as well.
 - any potential conflicts with other config options and so forth.

**Comment by piersmyers** [comment]
Hi @JanDeDobbeleer, how do I get this new gitdir feature to work, I currently have this segment:

```yaml
- type: path
  style: plain
  foreground: 'p:brightWhite'
  template: ' {{ path .Path .Location }}'
  properties:
    style: full
    edge_format: '<p:brightYellow>%s</>'
    gitdir_format: '<p:brightRed>%s</>'
    cycle:
      - 'p:brightCyan'
      - 'p:brightGreen'
```
but it is not formatting the git dir in red. Please give examples of how it should work.

**Comment by JanDeDobbeleer** [comment]
@piersmyers that should be it provided you're on the right version.

**Comment by piersmyers** [comment]
> @piersmyers that should be it provided you're on the right version.

I am using the latest version - 19.20.0 - do you have an example that works for you that I can try?

**Comment by stevenxxiu** [comment]
> > @piersmyers that should be it provided you're on the right version.
> 
> I am using the latest version - 19.20.0 - do you have an example that works for you that I can try?

Your formatting appear to be wrong. Here is my config, which works for me:

```yaml
gitdir_format: '<b><lightYellow>%s</></b>'
```

**Comment by piersmyers** [comment]
> > > @piersmyers that should be it provided you're on the right version.
> > 
> > 
> > I am using the latest version - 19.20.0 - do you have an example that works for you that I can try?
> 
> Your formatting appear to be wrong. Here is my config, which works for me:
> 
> ```yaml
> gitdir_format: '<b><lightYellow>%s</></b>'
> ```

@stevenxxiu - that still doesn't work for me. I have the edge_format set to '<p:brightYellow>%s</>' and that works fine. Even if I set my gitdir_format to 'XXX%sXXX' it won't surround my git repo name in the path with X's.

@JanDeDobbeleer - any help on this please?

**Comment by JanDeDobbeleer** [comment]
@piersmyers I'll have a look when I'm back from my holidays. Didn't bring my laptop 😉

**Comment by piersmyers** [comment]
> @piersmyers I'll have a look when I'm back from my holidays. Didn't bring my laptop 😉

@JanDeDobbeleer Have fun (in the sun?) 😎

**Comment by piersmyers** [comment]
Hi @JanDeDobbeleer , now that you're fully refreshed could you spare a little time a look at this new feature of yours that's not working for me. I am running oh-my-posh 19.21.0 on Windows 11 Terminal with PowerShell 7.4.2.

**Comment by JanDeDobbeleer** [comment]
@piersmyers it's still on my list, don't worry 😉

**Comment by JanDeDobbeleer** [comment]
@piersmyers i don't know what to say. This work on my machine using your config.

```yaml
      - type: path
        style: powerline
        powerline_symbol: 
        foreground: "#2d3436"
        background: "#FF9248"
        template: ' {{ path .Path .Location }}'
        properties:
          style: full
          edge_format: "<yellow>%s</>"
          gitdir_format: "<blue>%s</>"
          cycle:
            - 'p:orange'
            - 'p:white'
```

<img width="474" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/2492783/65c4d5e2-2720-403c-93b1-a6faef17676a">

<img width="529" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/2492783/6b28beb9-f3c6-4d45-9863-047d354b23c7">
