### ISSUE TITLE
New segment request: Talosctl current context

### ISSUE THREAD

**Issue by divanikus** [JanDeDobbeleer/oh-my-posh#4879]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be cool to have Talos OS's talosctl current context (https://www.talos.dev/v1.7/reference/cli/)

It should be quite simple - it's just `talosctl config info` or `context:` in `.talos/config`

**Comment by ivan-the-terrible** [comment]
Reading through the documentation and trying to get familiarized with this. I see the references to the `~/.talos/config` file that `talosctl config info` would pull from.

@divanikus do you have a sample config file you could provide that contains the `context` property? I see a flag that shows it can output the context info in different formats, but I'd rather read directly from the config file.

There are similar segments that pull from config files, so this isn't a difficult thing to implement.

If you can show me the format of the data, I can build the segment for you. Talos Linux sounds neat btw. Never heard of it before seeing this issue.

**Comment by divanikus** [comment]
Sure, it's a pretty simple YAML:
```
context: dev
contexts:
    dev:
        endpoints:
            - 10.1.0.10
        nodes:
            - 10.1.0.10
            - 10.1.0.20
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBNFM1ZGt4S2djV09hQmRCRmtPSktJVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOVEF4TVRjeE5UUXdXaGNOTXpRd05ESTVNVGN4TlRRd1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQVBhVEpUWXUzUTBHVHlpMUJtSXNBRmQwRTZXWUVUREpyemQyCi9kL3BlOXFRbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkhRd0FpSS9YbTVYUFdoQwpXOVU3enZQNlE1aDJNQVVHQXl0bGNBTkJBQVRxZDUyWWxoTW5odVd0dGhaTkI3cDNUKzl2SDk1RXdkb3ZmRHNxCkE0UFRTY1FnSUxtV3FLUkp2TjYvcHowNUxXSnNPNkZEN1kyNVoveHMzd2ltTmc4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLRENCMjZBREFnRUNBaEJVaGxNRWh5TldQS2QvNHY3aWpYU2JNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQTFNREV4TnpFMk1UZGFGdzB5TlRBMU1ERXhOekUyTVRkYU1CTXhFVEFQQmdOVgpCQW9UQ0c5ek9tRmtiV2x1TUNvd0JRWURLMlZ3QXlFQVBrNWxhNU80NEhnYi9zT2RJREdYUTNYekxaNERRTDdtCkNSR0pTNWVvd3RhalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0QKQWpBZkJnTlZIU01FR0RBV2dCUjBNQUlpUDE1dVZ6MW9RbHZWTzg3eitrT1lkakFGQmdNclpYQURRUURER1oxUQpJZWFPL3B3dlFBSFBUT1BoMk01TmUrUG1jRnFXbTdUMnFUcWpTeHJ5THgvRWVzWmwzOWw2UlNka3VmWkdNSkxQCkxsZjBkYUEzZEswZmUrY0kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTEE2a2htQkZzUXNlbE5yaVBySzJmZVNYWGlrSUJyZFRnT3NCUVFZVEhiYgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    prd:
        endpoints:
            - 10.2.0.10
            - 10.2.0.11
            - 10.2.0.12
        nodes:
            - 10.2.0.10
            - 10.2.0.11
            - 10.2.0.12
            - 10.2.1.10
            - 10.2.1.11
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEI2RXBydmhQNjdBWW1pVWxrajhyditNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQTFNREV4TnpFMU5UaGFGdzB6TkRBME1qa3hOekUxTlRoYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBaGtFREVPbk5TTTkxaTZEeGUyRVgzN2RKRlErTVF1Z25ZcGNECmNUV0FmOW1qWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVVXA5dC8yNmcwVmV2ZWo0agpvd0xjbi94YmR1UXdCUVlESzJWd0EwRUF3NEVwNk45L2NGUWpCVDkvN2FsNmVjb2JJSTlkRFRycG9wRUdXQXV3Cndjb2NraFEzWFd0TVhrL0lZamd5bmZEeVViK2hHek5BYzJocXpmK01XOG5ZRGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLRENCMjZBREFnRUNBaEFWaGZVdDFnTHl2dHVORjlnUFo5OHdNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5EQTFNREV4TnpFMk1qaGFGdzB5TlRBMU1ERXhOekUyTWpoYU1CTXhFVEFQQmdOVgpCQW9UQ0c5ek9tRmtiV2x1TUNvd0JRWURLMlZ3QXlFQWdIV1JoS3A3Z1dORzhEMFZwQmJ3TUlDYWx2dTF6djR0ClFMeFRKTDBCTVlPalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0QKQWpBZkJnTlZIU01FR0RBV2dCUlNuMjMvYnFEUlY2OTZQaU9qQXR5Zi9GdDI1REFGQmdNclpYQURRUUNqNmo5dApvWG5aZGNKWml6LytncjZRUEVxcm9uSWJ3bmlGZmJoUjNldmc0YWM2VkdDRzVqV21KL3RhNTUyVXZyRTRJY0lKCjFJQU81ZEU5anFRR3BLQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTnZIRnZZU0hrWGhkUmZka2lpVk9vWVJuMjRWRjRiUnZTMHU0dXV0N1diRwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
```
This is a sample config, keys are not from any existing cluster, so no worries.
