### ISSUE TITLE
YAML bare tilde value must be quoted

### ISSUE THREAD

**Issue by Bilge** [JanDeDobbeleer/oh-my-posh#5092]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When outputting the config in YAML format, the default value for `path.properties.home_icon` is the tilde (`~`), but the bare tilde value is interpreted as a special value by the YAML parser:

That is,

```yaml
  - type: path
    properties:
      home_icon: ~
```

Must actually be quoted or otherwise escaped as in:

```yaml
  - type: path
    properties:
      home_icon: '~'
```

If this is not done, it is [treated as _null_](https://yaml.org/spec/1.2-old/spec.html#id2805071) and the home icon simply disappears.

### Theme

[powerlevel10k_rainbow](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/powerlevel10k_rainbow.omp.json)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
~
```
