### ISSUE TITLE
Allow variables as input for the `max_width` property for the `path` segment.

### ISSUE THREAD

**Issue by awerebea** [JanDeDobbeleer/oh-my-posh#5097]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

I'm using the `powerlevel` style for the `path` segment because I want it to shorten long paths so they fit on one line in my current terminal window.

It would be great if I could set the value of the `path` segment's `max_width` property dynamically based on the width of my current terminal window, so as not to shorten paths that already fit into the current screen width.

``` yaml
- type: prompt
  alignment: left
  segments:
  - type: path
    style: plain
    properties:
      style: powerlevel
      max_width: "{{ .Env.POSH_MAX_PATH_WIDTH }}"
    template: "{{ .Path }}"
```
