### ISSUE TITLE
Adaptative Git Path

### ISSUE THREAD

**Issue by ebiscaia** [JanDeDobbeleer/oh-my-posh#5341]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

Hi guys,

I would like to when I am inside a git folder, the path to be started from the git root.
So I would have three conditions:
If I am inside a system folder, the path would look like:
`/this/is/a/folder`
If inside home:
`~/this/is/a/folder`
If inside a git folder:
`<git_folder>/this/is/a/folder`

I would prefer also that to be compatible/implemented with Agnoster short, so that long paths would show only the root/home/<git_folder> and the final folder. The idea is to mimic this [behaviour](https://typewritten.dev/#/prompt_customization) (See 'Adaptive (git and home) (TYPEWRITTEN_RELATIVE_PATH="adaptive")' section).

Thanks,

**Comment by vagabondHustler** [comment]
Do you mean this? https://github.com/JanDeDobbeleer/oh-my-posh/discussions/5186

**Comment by JanDeDobbeleer** [comment]
@vagabondHustler exactly what I was about to reply!

@holopin-bot @vagabondHustler helping

**Comment by ebiscaia** [comment]
Thanks everyone for the help. The version in the other post led me to what I wanted. Here is my version:

```
- type: rprompt
  segments:
  - type: path
    style: plain
    foreground: magenta
    template: "{{ if .Segments.Git.Dir }}<i>{{ .Segments.Git.RepoName }}</i>{{ if eq .Path .Segments.Git.Dir }}{{ else if eq (trimSuffix \"/\" .Parent) .Segments.Git.Dir }}/{{.Folder}}{{else}}/../{{.Folder}}{{end}}{{ else }}{{ .Path  }}{{ end }}"
    properties:
      style: agnoster_short
```
