### ISSUE TITLE
Show current mode in ZSH Vi mode

### ISSUE THREAD

**Issue by stepanzak** [JanDeDobbeleer/oh-my-posh#5438]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

In ZSH, you can enable Vi mode with `bindkey -v`.
Powerlevel10k has (had) a feature that shows current mode (`normal`/`insert`/`replace` etc.) and immediately updates it on change.
I would love to be able to do the same in omp, since it's really annoying to use the Vi mode whilst not being able to tell whether I'm in `insert` mode or not.

**Comment by gwojan** [comment]
Is there any way this feature could be added to `bash` Vi mode and `pwsh` for that matter? For PowerShell/PSReadLine I currently have a `ViModeChangeHandler` configured and it would be easy to set an environment variable that oh-my-posh could read.

**Comment by JanDeDobbeleer** [comment]
@stepanzak I was playing around with this and adding the following snippet already enables this. Currently thinking about how to enable that from the configuration.

### .zshrc

```zsh
bindkey -v

_omp_redraw-prompt() {
  local precmd
  for precmd in $precmd_functions; do
    $precmd
  done

  zle .reset-prompt
}

function _omp_zle-keymap-select() {
    if [ "${KEYMAP}" = 'vicmd' ]; then
        export POSH_VI_MODE="command"
    else
        export POSH_VI_MODE="insert"
    fi

    _omp_redraw-prompt
}
_omp_create_widget zle-keymap-select _omp_zle-keymap-select

# reset to default mode at the end of line input reading
function _omp_zle-line-finish() {
    export POSH_VI_MODE="insert"
}
_omp_create_widget zle-line-finish _omp_zle-line-finish

# Fix a bug when you C-c in CMD mode, you'd be prompted with CMD mode indicator
# while in fact you would be in INS mode.
# Fixed by catching SIGINT (C-c), set mode to INS and repropagate the SIGINT,
# so if anything else depends on it, we will not break it.
TRAPINT() {
    export POSH_VI_MODE="insert"
    return $(( 128 + $1 ))
}
```

And use the following code block to display this:

### mytheme.omp.json

```json
{
  "type": "text",
  "style": "plain",
  "template": "{{ if .Env.POSH_VI_MODE }}({{ .Env.POSH_VI_MODE }}) {{ end }}"
}
```

**Comment by NovaViper** [comment]
Hey, would it be possible for you to also make it where the prompt symbol can change based on what mode we're in? Possibly integrate with the [zsh-vi-mode plugin](https://github.com/jeffreytse/zsh-vi-mode) as an additional nicety!

**Comment by JanDeDobbeleer** [comment]
> integrate with the [zsh-vi-mode plugin](https://github.com/jeffreytse/zsh-vi-mode) as an additional nicety!

@NovaViper that's not something we do, but changing the icon is rather straightforward with the use of a template

**Comment by NovaViper** [comment]
@JanDeDobbeleer Ah ok! I was wondering because I can't consistently get the variable to display in the prompt. I can get it to show `insert` but oddly can't get `command` to appear when I hit the escape key to enter normal mode; even with the zsh-vi-mode plugin removed. What happens is when I first load up the terminal, the variable is empty (not taking into account the current mode when I start up is in `viins`). And when I hit enter, it shows `insert`; but `command` under any circumstance does not show at all.

This is my zshrc (I'm using NixOS with Home-Manager to setup zsh), https://gist.github.com/NovaViper/6eeb096936b0c52290632986a3a18d38

**Comment by Frestein** [comment]
> Hey, would it be possible for you to also make it where the prompt symbol can change based on what mode we're in? Possibly integrate with the [zsh-vi-mode plugin](https://github.com/jeffreytse/zsh-vi-mode) as an additional nicety!

My solution:
![image](https://github.com/user-attachments/assets/aa681d78-a09f-4321-8260-895693bc26af)
![image](https://github.com/user-attachments/assets/c066ef49-fc61-4500-b5cb-7d047c3b2fa6)
![image](https://github.com/user-attachments/assets/f04a295d-2310-498c-a08b-989d3d76c6ad)
![image](https://github.com/user-attachments/assets/a837c7bf-5652-45f2-97e7-3aa8a0db0977)
![image](https://github.com/user-attachments/assets/af00e603-a23c-4191-babc-2e77fa885fe6)

```sh
# OMP zsh-vi-mode integration
_omp_redraw-prompt() {
  local precmd
  for precmd in "${precmd_functions[@]}"; do
    "$precmd"
  done

  zle .reset-prompt
}

export POSH_VI_MODE="I"

function zvm_after_select_vi_mode() {
  case $ZVM_MODE in
  $ZVM_MODE_NORMAL)
    POSH_VI_MODE="N"
    ;;
  $ZVM_MODE_INSERT)
    POSH_VI_MODE="I"
    ;;
  $ZVM_MODE_VISUAL)
    POSH_VI_MODE="V"
    ;;
  $ZVM_MODE_VISUAL_LINE)
    POSH_VI_MODE="V-L"
    ;;
  $ZVM_MODE_REPLACE)
    POSH_VI_MODE="R"
    ;;
  esac
  _omp_redraw-prompt
}
```
```toml
[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = '{{ if .Env.POSH_VI_MODE }}{{ .Env.POSH_VI_MODE }}{{ end }}'
foreground = 'red'
background = '#3C3836'
type = 'text'
style = 'diamond'
foreground_templates = [
  "{{if contains \"N\" .Env.POSH_VI_MODE}}blue{{end}}",
  "{{if contains \"I\" .Env.POSH_VI_MODE}}magenta{{end}}",
  "{{if contains \"V\" .Env.POSH_VI_MODE}}cyan{{end}}",
  "{{if contains \"V-L\" .Env.POSH_VI_MODE}}cyan{{end}}",
  "{{if contains \"R\" .Env.POSH_VI_MODE}}yellow{{end}}",
]
```
