### ISSUE TITLE
Python segment display_mode default doesn't match documentation

### ISSUE THREAD

**Issue by mgrubb** [JanDeDobbeleer/oh-my-posh#5596]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The documentation for the python segment shows that the value `context` is the default setting for the `display_mode` property.  After looking in the segment's code, the default seems to actually be `environment`.  It appears that `context` is consistently the default for other modules.

I've created two different fixes for this, one that fixes the segment default to match the documentation and another that fixes the documentation to reflect the code.

Let me know which approach you'd prefer and I can submit a pull request.
[fix/python-display-mode-doc](https://github.com/mgrubb/oh-my-posh/tree/fix/python-display-mode-doc)
[fix/python-default-display-mode](https://github.com/mgrubb/oh-my-posh/tree/fix/python-default-display-mode)

### Theme

Custom:
```toml
[[blocks.segments]]
type = 'python'
style = 'plain'
template = '{{ if not .Error }} 🐍 {{ if .Venv }}[{{ .Venv }}] {{ end }}{{ .Full }} {{ else }}{{ .Error }}{{ end }}'
[blocks.segments.properties]
display_mode = 'context'
```

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
none
```
