### ISSUE TITLE
Don't work on zsh termux

### ISSUE THREAD

**Issue by Rignchen** [JanDeDobbeleer/oh-my-posh#5659]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Every time I enter a command on my mobile phone's zsh, oh my posh sends me a huge error message and I doubt it's an error made by oh my posh ment for the user to understand
![Screenshot_20240923_172905_Termux](https://github.com/user-attachments/assets/6c49af84-51b4-4009-b76d-d8e061db1fdd)

### Theme

I use the theme from my [dotfiles](https://github.com/Rignchen/dotfile/tree/main/.config/oh-my-posh/theme.toml) wich is shared across all my computers and works fine on the other ones

```toml
console_title_template = "{{.UserName}}@{{.HostName}} : {{.Folder}}"
final_space = true
version = 2

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

    [[blocks.segments]]
    background = "#fbfbfb"
    background_templates = [ "{{ if eq .Code 0 }}#fbfbfb{{ else }}#c22{{ end }}" ]
    foreground = "#0077c2"
    foreground_templates = [ "{{ if eq .Code 0 }}#0077c2{{ else }}#632020{{ end }}" ]
    leading_diamond = ""
    style = "diamond"
    template = "{{ if eq .Code 0 }}{{.Icon}}{{ else }}{{ .Code }}{{ end }} "
    type = "os"

        [blocks.segments.properties]
        arch = ""
        debian = ""
        fedora = ""
        linux = ""
        macos = ""
        manjaro = ""
        opensuse = ""
        ubuntu = ""
        windows = ""

    [[blocks.segments]]
    background = "#fbfbfb"
    foreground = "#0077c2"
    powerline_symbol = ""
    style = "powerline"
    template = "{{ .UserName }}<#000000>@</><#e06c75>{{ .HostName }}</> "
    type = "session"

        [blocks.segments.properties]
        display_host = true

    [[blocks.segments]]
    background = "#e06c75"
    foreground = "#ffffff"
    powerline_symbol = ""
    style = "powerline"
    template = " ⠀"
    type = "root"

    [[blocks.segments]]
    background = "#0077c2"
    foreground = "#ffffff"
    powerline_symbol = ""
    style = "powerline"
    template = "  {{ .Path }} "
    type = "path"

        [blocks.segments.properties]
        folder_separator_icon = "/"
        home_icon = "~"
        max_depth = 2
        style = "letter"

    [[blocks.segments]]
    background = "#fffb38"
    background_templates = [
        "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}",
        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}",
        "{{ if gt .Ahead 0 }}#f17c37{{ end }}",
        "{{ if gt .Behind 0 }}#89d1dc{{ end }}"
    ]
    foreground = "#193549"
    powerline_symbol = ""
    style = "powerline"
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }} "
    type = "git"

        [blocks.segments.properties]
        fetch_stash_count = true
        fetch_status = true
        fetch_upstream_icon = true
```

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
SIGSYS: bad system call
PC=0x15b40 m=0 sigcode=1

goroutine 22 gp=0x4000103c00 m=0 mp=0xfd93c0 [syscall]:
syscall.Syscall6(0x1b7, 0xffffffffffffff9c, 0x4000145a40, 0x1, 0x200, 0x0, 0x0)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/syscall/syscall_linux.go:91 +0x2c fp=0x400011aa20 sp=0x400011a9c0 pc=0xd3d9c
syscall.faccessat2(0xffffffffffffff9c, {0x40001459e0?, 0x4000145a10?}, 0x1, 0x200)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x400011aa80 sp=0x400011aa20 pc=0xd08a4
syscall.Faccessat(0xffffffffffffff9c, {0x40001459e0, 0x27}, 0x1, 0x200)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/syscall/syscall_linux.go:167 +0x3c fp=0x400011ab60 sp=0x400011aa80 pc=0xcdfac
internal/syscall/unix.Eaccess(...)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x40001459e0, 0x27})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/os/exec/lp_unix.go:31 +0x58 fp=0x400011abb0 sp=0x400011ab60 pc=0x340818
os/exec.LookPath({0x87145e, 0x3})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/os/exec/lp_unix.go:71 +0x198 fp=0x400011ac50 sp=0x400011abb0 pc=0x340ac8
github.com/jandedobbeleer/oh-my-posh/src/runtime.(*Terminal).LookPath(...)
        D:/a/oh-my-posh/oh-my-posh/src/runtime/terminal_unix.go:144
github.com/jandedobbeleer/oh-my-posh/src/runtime.(*Terminal).CommandPath(0x400037a280, {0x87145e, 0x3})
        D:/a/oh-my-posh/oh-my-posh/src/runtime/terminal.go:386 +0xa4 fp=0x400011ad20 sp=0x400011ac50 pc=0x358694
github.com/jandedobbeleer/oh-my-posh/src/runtime.(*Terminal).HasCommand(0x400037a280, {0x87145e, 0x3})
        D:/a/oh-my-posh/oh-my-posh/src/runtime/terminal.go:399 +0x8c fp=0x400011ad90 sp=0x400011ad20 pc=0x35892c
github.com/jandedobbeleer/oh-my-posh/src/segments.(*scm).hasCommand(0x4000182480, {0x87145e, 0x3})
        D:/a/oh-my-posh/oh-my-posh/src/segments/scm.go:190 +0xf0 fp=0x400011ade0 sp=0x400011ad90 pc=0x6571e0
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Git).shouldDisplay(0x4000182480)
        D:/a/oh-my-posh/oh-my-posh/src/segments/git.go:308 +0x30 fp=0x400011ae30 sp=0x400011ade0 pc=0x63ac50
github.com/jandedobbeleer/oh-my-posh/src/segments.(*Git).Enabled(0x4000182480)
        D:/a/oh-my-posh/oh-my-posh/src/segments/git.go:172 +0x60 fp=0x400011ae70 sp=0x400011ae30 pc=0x639ab0
github.com/jandedobbeleer/oh-my-posh/src/config.(*Segment).SetEnabled(0x4000102fc0, {0xa233c8, 0x400037a280})
        D:/a/oh-my-posh/oh-my-posh/src/config/segment.go:131 +0x2a4 fp=0x400011af60 sp=0x400011ae70 pc=0x67eb34
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).setEnabledSegments.func1(0x0?)
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:93 +0x58 fp=0x400011afb0 sp=0x400011af60 pc=0x678578
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).setEnabledSegments.gowrap2()
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:94 +0x30 fp=0x400011afd0 sp=0x400011afb0 pc=0x6784e0
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400011afd0 sp=0x400011afd0 pc=0x81bf4
created by github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).setEnabledSegments in goroutine 1
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:91 +0x94

goroutine 1 gp=0x40000021c0 m=nil [semacquire]:
runtime.gopark(0xfe2460?, 0x2028c?, 0x0?, 0x40?, 0x6?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:402 +0xc8 fp=0x400038f360 sp=0x400038f340 pc=0x4d6f8
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:408
runtime.semacquire1(0x400036b578, 0x0, 0x1, 0x0, 0x12)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/sema.go:160 +0x208 fp=0x400038f3b0 sp=0x400038f360 pc=0x60f58
sync.runtime_Semacquire(0x400038f408?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/sema.go:62 +0x2c fp=0x400038f3f0 sp=0x400038f3b0 pc=0x7d9cc
sync.(*WaitGroup).Wait(0x400036b570)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/sync/waitgroup.go:116 +0x74 fp=0x400038f410 sp=0x400038f3f0 pc=0xa0fe4
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).setEnabledSegments.deferwrap1()
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:88 +0x28 fp=0x400038f430 sp=0x400038f410 pc=0x678648
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).setEnabledSegments(0x400014c8f0)
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:96 +0x168 fp=0x400038f4b0 sp=0x400038f430 pc=0x678478
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).executeSegmentLogic(0x400014c8f0)
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:81 +0x4c fp=0x400038f4e0 sp=0x400038f4b0 pc=0x6782dc
github.com/jandedobbeleer/oh-my-posh/src/config.(*Block).Init(...)
        D:/a/oh-my-posh/oh-my-posh/src/config/block.go:59
github.com/jandedobbeleer/oh-my-posh/src/prompt.(*Engine).renderBlock(0x400038fc10, 0x400014c8f0, 0x0)
        D:/a/oh-my-posh/oh-my-posh/src/prompt/engine.go:194 +0xfc fp=0x400038f620 sp=0x400038f4e0 pc=0x70816c
github.com/jandedobbeleer/oh-my-posh/src/prompt.(*Engine).writePrimaryPrompt(0x400038fc10, 0x1)
        D:/a/oh-my-posh/oh-my-posh/src/prompt/primary.go:72 +0x424 fp=0x400038f760 sp=0x400038f620 pc=0x70b8c4
github.com/jandedobbeleer/oh-my-posh/src/prompt.(*Engine).Primary(0x400038fc10)
        D:/a/oh-my-posh/oh-my-posh/src/prompt/primary.go:15 +0xfc fp=0x400038f7c0 sp=0x400038f760 pc=0x70b1bc
github.com/jandedobbeleer/oh-my-posh/src/prompt.(*Engine).PrintDebug(0x400038fc10, {0x400037a280?, 0xa233c8?, 0xfd6e80?}, {0xa0b0f8, 0x7})
        D:/a/oh-my-posh/oh-my-posh/src/prompt/debug.go:36 +0x7d0 fp=0x400038fb90 sp=0x400038f7c0 pc=0x706380
github.com/jandedobbeleer/oh-my-posh/src/cli.createDebugCmd.func1(0x4000368608, {0x40001a9740, 0x1, 0x871aac?})
        D:/a/oh-my-posh/oh-my-posh/src/cli/debug.go:68 +0x2a0 fp=0x400038fca0 sp=0x400038fb90 pc=0x7128f0
github.com/spf13/cobra.(*Command).execute(0x4000368608, {0x40001a9720, 0x2, 0x2})
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x828 fp=0x400038fe30 sp=0x400038fca0 pc=0x1d2b78
github.com/spf13/cobra.(*Command).ExecuteC(0xfb4240)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344 fp=0x400038ff10 sp=0x400038fe30 pc=0x1d3354
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/jandedobbeleer/oh-my-posh/src/cli.Execute()
        D:/a/oh-my-posh/oh-my-posh/src/cli/root.go:38 +0x24 fp=0x400038ff30 sp=0x400038ff10 pc=0x711b64
main.main()
        D:/a/oh-my-posh/oh-my-posh/src/main.go:6 +0x1c fp=0x400038ff40 sp=0x400038ff30 pc=0x712a9c
runtime.main()
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:271 +0x28c fp=0x400038ffd0 sp=0x400038ff40 pc=0x4d2cc
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400038ffd0 sp=0x400038ffd0 pc=0x81bf4

goroutine 2 gp=0x4000002700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:402 +0xc8 fp=0x4000070f90 sp=0x4000070f70 pc=0x4d6f8
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:408
runtime.forcegchelper()
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:326 +0xb8 fp=0x4000070fd0 sp=0x4000070f90 pc=0x4d588
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000070fd0 sp=0x4000070fd0 pc=0x81bf4
created by runtime.init.6 in goroutine 1
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:314 +0x24

goroutine 3 gp=0x4000002c40 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:402 +0xc8 fp=0x4000071760 sp=0x4000071740 pc=0x4d6f8
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:408
runtime.bgsweep(0x4000090000)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgcsweep.go:278 +0xa0 fp=0x40000717b0 sp=0x4000071760 pc=0x38c50
runtime.gcenable.gowrap1()
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgc.go:203 +0x28 fp=0x40000717d0 sp=0x40000717b0 pc=0x2ce68
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40000717d0 sp=0x40000717d0 pc=0x81bf4
created by runtime.gcenable in goroutine 1
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgc.go:203 +0x6c

goroutine 4 gp=0x4000002e00 m=nil [GC scavenge wait]:
runtime.gopark(0x4000090000?, 0xa07c90?, 0x1?, 0x0?, 0x4000002e00?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:402 +0xc8 fp=0x4000071f60 sp=0x4000071f40 pc=0x4d6f8
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:408
runtime.(*scavengerState).park(0xfd70a0)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgcscavenge.go:425 +0x5c fp=0x4000071f90 sp=0x4000071f60 pc=0x3664c
runtime.bgscavenge(0x4000090000)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgcscavenge.go:653 +0x44 fp=0x4000071fb0 sp=0x4000071f90 pc=0x36b94
runtime.gcenable.gowrap2()
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgc.go:204 +0x28 fp=0x4000071fd0 sp=0x4000071fb0 pc=0x2ce08
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000071fd0 sp=0x4000071fd0 pc=0x81bf4
created by runtime.gcenable in goroutine 1
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mgc.go:204 +0xac

goroutine 17 gp=0x4000102380 m=nil [finalizer wait]:
runtime.gopark(0x60?, 0x7f22f6aa48?, 0xc8?, 0x5?, 0x28994?)
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/proc.go:402 +0xc8 fp=0x4000070580 sp=0x4000070560 pc=0x4d6f8
runtime.runfinq()
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mfinal.go:194 +0x108 fp=0x40000707d0 sp=0x4000070580 pc=0x2bf38
runtime.goexit({})
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40000707d0 sp=0x40000707d0 pc=0x81bf4
created by runtime.createfing in goroutine 1
        C:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/mfinal.go:164 +0x80

r0      0xffffffffffffff9c
r1      0x4000145a40
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2e6d6f632f617461
r11     0x662f78756d726574
r12     0x7273752f73656c69
r13     0x7469672f6e69622f
r14     0x8c
r15     0x8d
r16     0xaa
r17     0x400011a980
r18     0x0
r19     0xe10
r20     0x400011abe0
r21     0xfd93c0
r22     0x4000004000
r23     0x5a
r24     0x400016c2c8
r25     0x0
r26     0x8ea608
r27     0x1
r28     0x4000103c00
r29     0x400011a958
lr      0x15afc
sp      0x400011a960
pc      0x15b40
fault   0x0
```
