### ISSUE TITLE
Status segment hangs with a condition

### ISSUE THREAD

**Issue by stevenxxiu** [JanDeDobbeleer/oh-my-posh#5816]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The latest version v24.0.5 hangs when the `status` segment has some condition.

### Theme

Minimal config:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 3
blocks:
  - type: prompt
    segments:
      - type: status
        templates:
          - '{{ if .Segments.Contains "Executiontime" }}a{{ else }}b{{ end }}'
```

### What OS are you seeing the problem on?

*Arch Linux*

### Which shell are you using?

*Nushell*

### Log output
This hangs, so I can't get log output.
