### ISSUE TITLE
Incorrect TOML config samples

### ISSUE THREAD

**Issue by shfrmn** [JanDeDobbeleer/oh-my-posh#6304]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Below is the currently featured TOML sample for the git segment (abbreviated for clarity), but the issue is relevant for all TOML samples on the website.

```toml
type = "git"
style = "powerline"
# ...

[properties]
fetch_status = true
fetch_upstream_icon = true
source = "cli"
```

The problem here is that `[properties]` should in fact be `[blocks.segments.properties]`, otherwise they are simply ignored. The issue is quite subtle and not immediately obvious when copy-pasting a snippet, which wastes a lot of user time. 

If I understand correctly, TOML snippets are being converted from JSON, so there has to be some way to fix this in the build process. 

Let me know if this makes sense and thank you very much for your work on oh-my-posh!
