### ISSUE TITLE
Add x86 installer to winget manifest

### ISSUE THREAD

**Issue by kfarnung** [JanDeDobbeleer/oh-my-posh#898]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I've started using winget as a part of my workflow and I'm also using an ARM64 Windows device. I tried installing using `winget install ohmyposh`, but it failed due to not having an x86 version in the manifest.

I found the [manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/j/JanDeDobbeleer/OhMyPosh/3.172.1/JanDeDobbeleer.OhMyPosh.installer.yaml) and manually downloaded the installer. The installer seems to support both x86 and x64, but it looks like the manifest will need to have duplicate entries for the same installer, just differing by architecture:

```yaml
# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: JanDeDobbeleer.OhMyPosh
PackageVersion: 3.172.1
InstallModes:
- silent
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.172.1/install.exe
  InstallerSha256: 694B9454C37F695F4B733277FB93B89BCF67EC5B4AB2987C1CD7D1E097DD8958
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.172.1/install.exe
  InstallerSha256: 694B9454C37F695F4B733277FB93B89BCF67EC5B4AB2987C1CD7D1E097DD8958
ManifestType: installer
ManifestVersion: 1.0.0
```

Is this something that has already been considered?
